AHUB API:ERROR [Nov-23-2022 16:25:58] OTP Error: {"message":"getaddrinfo EAI_AGAIN us.sms.api.sinch.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN us.sms.api.sinch.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:725:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2467:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","Authorization":"Bearer d0f03e6c80df4e97b74feda4ac1d092f","User-Agent":"axios/1.1.3","Content-Length":"82","Accept-Encoding":"gzip, deflate, br"},"method":"post","url":"https://us.sms.api.sinch.com/xms/v1/e0c81087c4a5433394bf1607b2c5a86a/batches","data":"{\"from\":\"+12064743920\",\"to\":[\"+2348034074748\"],\"body\":\"your OTP [object Promise]\"}"},"code":"EAI_AGAIN","status":null}
AHUB API:ERROR [Nov-23-2022 16:25:58] Error creating Patron : {"message":"getaddrinfo EAI_AGAIN us.sms.api.sinch.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN us.sms.api.sinch.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:725:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2467:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","Authorization":"Bearer d0f03e6c80df4e97b74feda4ac1d092f","User-Agent":"axios/1.1.3","Content-Length":"82","Accept-Encoding":"gzip, deflate, br"},"method":"post","url":"https://us.sms.api.sinch.com/xms/v1/e0c81087c4a5433394bf1607b2c5a86a/batches","data":"{\"from\":\"+12064743920\",\"to\":[\"+2348034074748\"],\"body\":\"your OTP [object Promise]\"}"},"code":"EAI_AGAIN","status":null}  ðŸ˜ 
AHUB API:ERROR [Nov-23-2022 16:27:36] Login failed. Please try again later.: Error: Invalid login credentials
AHUB API:ERROR [Nov-23-2022 16:31:04] OTP Error: {"message":"getaddrinfo EAI_AGAIN us.sms.api.sinch.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN us.sms.api.sinch.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:725:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2467:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","Authorization":"Bearer d0f03e6c80df4e97b74feda4ac1d092f","User-Agent":"axios/1.1.3","Content-Length":"82","Accept-Encoding":"gzip, deflate, br"},"method":"post","url":"https://us.sms.api.sinch.com/xms/v1/e0c81087c4a5433394bf1607b2c5a86a/batches","data":"{\"from\":\"+12064743920\",\"to\":[\"+2348034074748\"],\"body\":\"your OTP [object Promise]\"}"},"code":"EAI_AGAIN","status":null}
AHUB API:ERROR [Nov-23-2022 16:31:12] OTP Error: {"message":"getaddrinfo EAI_AGAIN us.sms.api.sinch.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN us.sms.api.sinch.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:725:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2467:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","Authorization":"Bearer d0f03e6c80df4e97b74feda4ac1d092f","User-Agent":"axios/1.1.3","Content-Length":"82","Accept-Encoding":"gzip, deflate, br"},"method":"post","url":"https://us.sms.api.sinch.com/xms/v1/e0c81087c4a5433394bf1607b2c5a86a/batches","data":"{\"from\":\"+12064743920\",\"to\":[\"+2348034074748\"],\"body\":\"your OTP [object Promise]\"}"},"code":"EAI_AGAIN","status":null}
AHUB API:ERROR [Nov-23-2022 16:31:17] OTP Error: {"message":"getaddrinfo EAI_AGAIN us.sms.api.sinch.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN us.sms.api.sinch.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:725:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2467:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","Authorization":"Bearer d0f03e6c80df4e97b74feda4ac1d092f","User-Agent":"axios/1.1.3","Content-Length":"82","Accept-Encoding":"gzip, deflate, br"},"method":"post","url":"https://us.sms.api.sinch.com/xms/v1/e0c81087c4a5433394bf1607b2c5a86a/batches","data":"{\"from\":\"+12064743920\",\"to\":[\"+2348034074748\"],\"body\":\"your OTP [object Promise]\"}"},"code":"EAI_AGAIN","status":null}
AHUB API:ERROR [Nov-23-2022 16:31:19] OTP Error: {"message":"getaddrinfo EAI_AGAIN us.sms.api.sinch.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN us.sms.api.sinch.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:725:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2467:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","Authorization":"Bearer d0f03e6c80df4e97b74feda4ac1d092f","User-Agent":"axios/1.1.3","Content-Length":"82","Accept-Encoding":"gzip, deflate, br"},"method":"post","url":"https://us.sms.api.sinch.com/xms/v1/e0c81087c4a5433394bf1607b2c5a86a/batches","data":"{\"from\":\"+12064743920\",\"to\":[\"+2348034074748\"],\"body\":\"your OTP [object Promise]\"}"},"code":"EAI_AGAIN","status":null}
AHUB API:ERROR [Nov-23-2022 16:43:47] OTP Error: {"message":"getaddrinfo EAI_AGAIN us.sms.api.sinch.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN us.sms.api.sinch.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:725:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2467:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","Authorization":"Bearer d0f03e6c80df4e97b74feda4ac1d092f","User-Agent":"axios/1.1.3","Content-Length":"82","Accept-Encoding":"gzip, deflate, br"},"method":"post","url":"https://us.sms.api.sinch.com/xms/v1/e0c81087c4a5433394bf1607b2c5a86a/batches","data":"{\"from\":\"+12064743920\",\"to\":[\"+2348034074748\"],\"body\":\"your OTP [object Promise]\"}"},"code":"EAI_AGAIN","status":null}
AHUB API:ERROR [Nov-23-2022 16:43:47] Error creating Patron : {"message":"getaddrinfo EAI_AGAIN us.sms.api.sinch.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN us.sms.api.sinch.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:725:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2467:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","Authorization":"Bearer d0f03e6c80df4e97b74feda4ac1d092f","User-Agent":"axios/1.1.3","Content-Length":"82","Accept-Encoding":"gzip, deflate, br"},"method":"post","url":"https://us.sms.api.sinch.com/xms/v1/e0c81087c4a5433394bf1607b2c5a86a/batches","data":"{\"from\":\"+12064743920\",\"to\":[\"+2348034074748\"],\"body\":\"your OTP [object Promise]\"}"},"code":"EAI_AGAIN","status":null}  ðŸ˜ 
AHUB API:ERROR [Nov-23-2022 16:54:35] OTP Error: {"message":"getaddrinfo EAI_AGAIN us.sms.api.sinch.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN us.sms.api.sinch.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:725:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2467:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","Authorization":"Bearer d0f03e6c80df4e97b74feda4ac1d092f","User-Agent":"axios/1.1.3","Content-Length":"82","Accept-Encoding":"gzip, deflate, br"},"method":"post","url":"https://us.sms.api.sinch.com/xms/v1/e0c81087c4a5433394bf1607b2c5a86a/batches","data":"{\"from\":\"+12064743920\",\"to\":[\"+2348034074748\"],\"body\":\"your OTP [object Promise]\"}"},"code":"EAI_AGAIN","status":null}
AHUB API:ERROR [Nov-23-2022 16:56:39] OTP Error: {"message":"getaddrinfo EAI_AGAIN us.sms.api.sinch.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN us.sms.api.sinch.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:725:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2467:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","Authorization":"Bearer d0f03e6c80df4e97b74feda4ac1d092f","User-Agent":"axios/1.1.3","Content-Length":"82","Accept-Encoding":"gzip, deflate, br"},"method":"post","url":"https://us.sms.api.sinch.com/xms/v1/e0c81087c4a5433394bf1607b2c5a86a/batches","data":"{\"from\":\"+12064743920\",\"to\":[\"+2348034074748\"],\"body\":\"your OTP [object Promise]\"}"},"code":"EAI_AGAIN","status":null}
AHUB API:ERROR [Nov-23-2022 16:56:43] OTP Error: {"message":"getaddrinfo EAI_AGAIN us.sms.api.sinch.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN us.sms.api.sinch.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:725:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2467:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","Authorization":"Bearer d0f03e6c80df4e97b74feda4ac1d092f","User-Agent":"axios/1.1.3","Content-Length":"82","Accept-Encoding":"gzip, deflate, br"},"method":"post","url":"https://us.sms.api.sinch.com/xms/v1/e0c81087c4a5433394bf1607b2c5a86a/batches","data":"{\"from\":\"+12064743920\",\"to\":[\"+2348034074748\"],\"body\":\"your OTP [object Promise]\"}"},"code":"EAI_AGAIN","status":null}
AHUB API:ERROR [Nov-23-2022 16:56:44] Error generating OTP: {"clientVersion":"4.6.1"}
AHUB API:ERROR [Nov-23-2022 18:19:29] OTP Error: {"message":"getaddrinfo EAI_AGAIN us.sms.api.sinch.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN us.sms.api.sinch.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:725:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2467:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","Authorization":"Bearer d0f03e6c80df4e97b74feda4ac1d092f","User-Agent":"axios/1.1.3","Content-Length":"82","Accept-Encoding":"gzip, deflate, br"},"method":"post","url":"https://us.sms.api.sinch.com/xms/v1/e0c81087c4a5433394bf1607b2c5a86a/batches","data":"{\"from\":\"+12064743920\",\"to\":[\"+2348034074748\"],\"body\":\"your OTP [object Promise]\"}"},"code":"EAI_AGAIN","status":null}
AHUB API:ERROR [Nov-23-2022 18:20:58] OTP Error: {"message":"getaddrinfo EAI_AGAIN us.sms.api.sinch.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN us.sms.api.sinch.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:725:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2467:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","Authorization":"Bearer d0f03e6c80df4e97b74feda4ac1d092f","User-Agent":"axios/1.1.3","Content-Length":"82","Accept-Encoding":"gzip, deflate, br"},"method":"post","url":"https://us.sms.api.sinch.com/xms/v1/e0c81087c4a5433394bf1607b2c5a86a/batches","data":"{\"from\":\"+12064743920\",\"to\":[\"+2348034074748\"],\"body\":\"your OTP [object Promise]\"}"},"code":"EAI_AGAIN","status":null}
AHUB API:ERROR [Nov-23-2022 18:22:07] OTP Error
AHUB API:ERROR [Nov-23-2022 18:35:37] OTP Error
AHUB API:ERROR [Nov-23-2022 18:35:41] OTP Error
AHUB API:ERROR [Nov-23-2022 18:35:43] OTP Error
AHUB API:ERROR [Nov-23-2022 18:35:45] OTP Error
AHUB API:ERROR [Nov-23-2022 18:35:46] OTP Error
AHUB API:ERROR [Nov-23-2022 18:35:48] Error generating OTP: {"code":"P2034","clientVersion":"4.6.1","meta":{}}
AHUB API:ERROR [Nov-23-2022 18:40:14] OTP Error
AHUB API:ERROR [Nov-23-2022 18:40:19] OTP Error
AHUB API:ERROR [Nov-23-2022 18:40:22] OTP Error
AHUB API:ERROR [Nov-23-2022 19:03:51] OTP Error
AHUB API:ERROR [Nov-23-2022 19:03:56] OTP Error
AHUB API:ERROR [Nov-23-2022 19:04:06] Error generating OTP: {"code":"P2034","clientVersion":"4.6.1","meta":{}}
AHUB API:ERROR [Nov-23-2022 23:00:54] Login failed. Please try again later.: Error: 
Invalid `prisma_1.Prisma.user.findUnique()` invocation in
E:\Projects\servers\ahub-api\dist\Controllers\AuthController.js:30:61

  27 try {
  28     //const data = await Cache.baseCache('login', async () => {
  29     Libs_1.Logger.info('Signing In.....');
â†’ 30     const user = yield prisma_1.Prisma.user.findUnique(
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: RawDatabaseError { code: "unknown", message: "This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server. (os error 11002)" } })
AHUB API:ERROR [Nov-23-2022 23:01:06] Login failed. Please try again later.: Error: 
Invalid `prisma_1.Prisma.user.findUnique()` invocation in
E:\Projects\servers\ahub-api\dist\Controllers\AuthController.js:30:61

  27 try {
  28     //const data = await Cache.baseCache('login', async () => {
  29     Libs_1.Logger.info('Signing In.....');
â†’ 30     const user = yield prisma_1.Prisma.user.findUnique(
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: RawDatabaseError { code: "unknown", message: "This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server. (os error 11002)" } })
AHUB API:ERROR [Nov-23-2022 23:01:12] Login failed. Please try again later.: Error: 
Invalid `prisma_1.Prisma.user.findUnique()` invocation in
E:\Projects\servers\ahub-api\dist\Controllers\AuthController.js:30:61

  27 try {
  28     //const data = await Cache.baseCache('login', async () => {
  29     Libs_1.Logger.info('Signing In.....');
â†’ 30     const user = yield prisma_1.Prisma.user.findUnique(
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: RawDatabaseError { code: "unknown", message: "This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server. (os error 11002)" } })
AHUB API:ERROR [Nov-24-2022 20:55:48] Cache Error: Error: The client is closed
AHUB API:ERROR [Nov-24-2022 20:56:43]  Error: The client is closed
AHUB API:ERROR [Nov-24-2022 20:57:10] Cache Error: The client is closed
AHUB API:ERROR [Nov-24-2022 20:57:41] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:41] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:41] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:41] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:41] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:41] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:42] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:42] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:42] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:43] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:43] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:44] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:44] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:45] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:45] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:46] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:46] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:47] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:47] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:48] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:48] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:49] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:49] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:50] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:51] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:51] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:52] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:52] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:53] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:53] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:54] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:54] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:55] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:13:59] Error connection to redis: Error: read ECONNRESET
AHUB API:ERROR [Nov-24-2022 21:14:01] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:01] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:01] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:01] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:01] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:01] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:02] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:02] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:02] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:03] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:03] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:04] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:09] Error connection to redis: Error: Connection timeout
AHUB API:ERROR [Nov-24-2022 21:14:15] Error connection to redis: Error: Connection timeout
AHUB API:ERROR [Nov-24-2022 21:14:18] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:18] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:19] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:19] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:20] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:20] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:21] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:21] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:22] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:27] Error connection to redis: Error: Connection timeout
AHUB API:ERROR [Nov-24-2022 21:22:12] Error connection to redis: Error: read ECONNRESET
AHUB API:ERROR [Nov-24-2022 21:22:16] Error connection to redis: Error: connect ECONNABORTED 54.92.223.199:10612
AHUB API:ERROR [Nov-24-2022 21:22:16] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:16] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:16] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:16] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:16] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:17] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:17] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:17] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:18] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:18] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:23] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:31] Error connection to redis: Error: Connection timeout
AHUB API:ERROR [Nov-24-2022 21:22:35] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:36] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:36] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:37] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:38] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:38] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:39] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:39] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:41] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:41] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:42] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:43] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:43] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:44] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:44] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:45] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:45] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:46] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:46] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:47] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:47] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:48] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:48] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:49] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:49] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:50] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:50] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:51] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:52] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:52] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:53] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:53] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:56] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:56] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:57] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:57] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:58] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:58] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:59] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:59] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:00] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:00] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:01] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:02] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:02] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:03] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:03] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:04] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:04] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:05] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:06] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:06] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:07] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:07] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:08] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:08] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:09] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:09] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:10] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:11] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 16:47:56] Error Connecting to Database: Error: Database error. error code: unknown, error message: Server selection timeout: No available servers. Topology: { Type: ReplicaSetNoPrimary, Servers: [ { Address: ac-vzis8uw-shard-00-01.qutaxg0.mongodb.net:27017, Type: Unknown, Error: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server. (os error 11002) }, { Address: ac-vzis8uw-shard-00-00.qutaxg0.mongodb.net:27017, Type: Unknown, Error: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server. (os error 11002) }, { Address: ac-vzis8uw-shard-00-02.qutaxg0.mongodb.net:27017, Type: Unknown, Error: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server. (os error 11002) }, ] }
AHUB API:ERROR [Nov-25-2022 16:49:30] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 16:49:30] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 16:49:30] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 16:49:30] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 16:49:30] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 16:49:30] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 16:49:31] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 16:49:31] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 16:49:31] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 16:49:32] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 16:49:32] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 16:49:33] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 16:49:33] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 16:49:34] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 16:49:34] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 16:49:35] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 16:49:35] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 16:49:36] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 16:49:36] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 16:49:37] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 16:49:37] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 16:49:38] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 16:49:38] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 16:49:39] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 16:49:40] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 16:49:40] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 16:49:41] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 16:49:41] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 16:49:42] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 16:49:42] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 16:49:43] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:04] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:04] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:05] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:05] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:05] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:05] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:05] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:06] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:06] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:11] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:11] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:11] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:11] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:11] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:11] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:11] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:12] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:12] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:12] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:13] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:13] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:14] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:14] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:15] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:16] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:16] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:17] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:17] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:21] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:21] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:21] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:21] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:21] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:21] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:21] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:22] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:22] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:23] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:23] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:24] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:24] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:25] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:25] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:26] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:26] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:27] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:27] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:28] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:28] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:29] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:29] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:28:30] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 17:29:54] Error Registering Patron : {"clientVersion":"4.6.1"}  ðŸ˜ 
AHUB API:ERROR [Nov-25-2022 18:24:52] Error Connecting to Database: Error: Database error. error code: unknown, error message: Server selection timeout: No available servers. Topology: { Type: ReplicaSetNoPrimary, Servers: [ { Address: ac-vzis8uw-shard-00-01.qutaxg0.mongodb.net:27017, Type: Unknown, Error: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server. (os error 11002) }, { Address: ac-vzis8uw-shard-00-00.qutaxg0.mongodb.net:27017, Type: Unknown, Error: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server. (os error 11002) }, { Address: ac-vzis8uw-shard-00-02.qutaxg0.mongodb.net:27017, Type: Unknown, Error: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server. (os error 11002) }, ] }
AHUB API:ERROR [Nov-25-2022 18:26:57] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:26:57] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:26:57] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:01] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:01] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:02] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:02] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:02] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:03] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:03] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:04] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:04] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:07] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:07] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:08] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:08] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:09] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:09] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:10] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:10] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:28] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:28] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:28] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:28] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:28] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:28] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:29] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:29] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:29] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:30] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:30] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:31] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:31] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:32] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:32] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:33] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:33] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:34] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:34] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:35] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:35] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:36] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:36] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:37] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:37] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:38] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:39] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:39] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:40] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:40] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:41] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:41] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:42] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:42] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:43] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:43] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:44] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:44] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:45] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:45] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:46] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:46] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:47] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:47] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:48] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:48] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:49] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:49] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:50] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:50] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:51] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:51] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:52] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:53] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:53] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:54] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:54] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:55] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:55] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:56] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:56] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:57] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:57] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:58] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:58] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:59] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:27:59] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:28:00] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:28:00] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:28:01] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:28:01] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:28:02] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:28:02] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:28:03] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:28:03] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:28:04] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:28:04] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:28:05] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:28:06] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:28:06] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:28:07] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:35:40] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:35:40] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:35:40] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:35:40] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:35:55] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:35:55] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:35:55] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:35:55] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:35:55] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:35:55] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:35:55] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:35:56] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:35:56] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:35:56] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:35:57] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:35:57] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:35:58] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:35:58] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:35:59] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:00] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:00] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:01] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:01] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:02] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:02] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:03] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:03] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:04] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:04] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:05] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:05] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:06] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:06] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:07] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:07] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:08] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:08] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:09] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:09] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:10] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:11] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:11] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:12] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:12] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:13] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:13] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:14] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:14] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:15] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:15] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:16] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:16] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:17] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:17] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:18] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:18] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 18:36:19] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 19:06:39] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 19:06:39] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 19:06:39] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 19:06:40] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 19:06:40] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 19:06:40] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 19:06:40] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 19:06:40] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 19:06:41] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 19:06:41] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 19:06:42] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 19:06:42] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 19:06:43] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 19:06:43] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 19:10:12] Error connection to redis: Error: read ECONNRESET
AHUB API:ERROR [Nov-25-2022 19:10:17] Error connection to redis: Error: Connection timeout
AHUB API:ERROR [Nov-25-2022 19:10:22] Error connection to redis: Error: Connection timeout
AHUB API:ERROR [Nov-25-2022 19:10:27] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 19:10:27] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 19:10:27] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 19:10:28] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 19:10:28] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 19:10:28] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 19:10:29] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 19:10:29] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 19:10:30] OTP Error
AHUB API:ERROR [Nov-25-2022 19:10:30] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 19:10:30] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 19:10:31] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 19:10:31] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-25-2022 19:10:32] Error generating OTP: {"clientVersion":"4.6.1"}
AHUB API:ERROR [Nov-25-2022 19:11:49] OTP Error
AHUB API:ERROR [Nov-25-2022 19:32:44] OTP Error
AHUB API:ERROR [Nov-25-2022 19:32:48] OTP Error
AHUB API:ERROR [Nov-25-2022 19:32:51] OTP Error
AHUB API:ERROR [Nov-25-2022 19:32:53] OTP Error
AHUB API:ERROR [Nov-25-2022 19:32:55] OTP Error
AHUB API:ERROR [Nov-25-2022 19:32:56] OTP Error
AHUB API:ERROR [Nov-25-2022 19:32:58] Error generating OTP: {"code":"P2034","clientVersion":"4.6.1","meta":{}}
AHUB API:ERROR [Nov-28-2022 22:51:40] Login failed. Please try again later.: Error: Invalid login credentials
AHUB API:ERROR [Nov-28-2022 22:53:25] Login failed. Please try again later.: Error: Invalid login credentials
AHUB API:ERROR [Nov-29-2022 01:08:12] Error fetching role (REDIS..): Error: 
Invalid `prisma_1.Prisma.role.findMany()` invocation in
E:\Projects\servers\ahub-api\dist\Services\UserService.js:39:57

  36 return __awaiter(this, void 0, void 0, function* () {
  37     try {
  38         // const roles = await Cache('roles', async () => {
â†’ 39         const data = yield prisma_1.Prisma.role.findMany(
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: RawDatabaseError { code: "unknown", message: "This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server. (os error 11002)" } })
AHUB API:ERROR [Nov-29-2022 01:08:14] Error Creating Role...
AHUB API:ERROR [Nov-29-2022 01:14:45] Login failed. Please try again later.: Error: Invalid login credentials
AHUB API:ERROR [Nov-29-2022 01:15:21] OTP Error
AHUB API:ERROR [Nov-29-2022 01:35:53] Login failed. Please try again later.: Error: Invalid login credentials
AHUB API:ERROR [Nov-29-2022 01:35:58] Login failed. Please try again later.: Error: Invalid login credentials
AHUB API:ERROR [Nov-29-2022 01:36:04] Login failed. Please try again later.: Error: Invalid login credentials
AHUB API:ERROR [Nov-29-2022 01:37:59] OTP Error
AHUB API:ERROR [Nov-29-2022 01:40:58] OTP Error
AHUB API:ERROR [Nov-29-2022 01:40:58] Error Registering Patron : {"message":"getaddrinfo EAI_AGAIN us.sms.api.sinch.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN us.sms.api.sinch.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:725:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2467:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","Authorization":"Bearer d0f03e6c80df4e97b74feda4ac1d092f","User-Agent":"axios/1.1.3","Content-Length":"82","Accept-Encoding":"gzip, deflate, br"},"method":"post","url":"https://us.sms.api.sinch.com/xms/v1/e0c81087c4a5433394bf1607b2c5a86a/batches","data":"{\"from\":\"+12064743920\",\"to\":[\"+2347082227861\"],\"body\":\"your OTP [object Promise]\"}"},"code":"EAI_AGAIN","status":null}  ðŸ˜ 
AHUB API:ERROR [Nov-29-2022 01:41:23] Error generating OTP: {"clientVersion":"4.6.1"}
AHUB API:ERROR [Dec-07-2022 20:02:11] Error Connecting to Database: Error: Error in connector: Error creating a database connection. (An error occurred during DNS resolution: no record found for name: _mongodb._tcp.cluster0.qutaxg0.mongodb.net. type: SRV class: IN)
AHUB API:ERROR [Dec-07-2022 20:06:27] Error Connecting to Database: Error: Query engine library for current platform "linux-musl" could not be found.
You incorrectly pinned it to linux-musl

This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "/app/node_modules/@prisma/client/runtime/libquery_engine-linux-musl.so.node")

Searched Locations:

  /app/node_modules/.prisma/client
  E:\Projects\servers\ahub-api\node_modules\@prisma\client
  /app/node_modules/@prisma/client
  /app/node_modules/.prisma/client
  /app/node_modules/.prisma/client
  /tmp/prisma-engines
  /app/node_modules/.prisma/client


To solve this problem, add the platform "linux-musl" to the "binaryTargets" attribute in the "generator" block in the "schema.prisma" file:
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native"]
}

Then run "prisma generate" for your changes to take effect.
Read more about deploying Prisma Client: https://pris.ly/d/client-generator
AHUB API:ERROR [Dec-07-2022 20:17:15] Error Connecting to Database: Error: Error in connector: Error creating a database connection. (An error occurred during DNS resolution: no record found for name: _mongodb._tcp.cluster0.qutaxg0.mongodb.net. type: SRV class: IN)
AHUB API:ERROR [Dec-07-2022 20:19:49] Error Connecting to Database: Error: Query engine library for current platform "linux-musl" could not be found.
You incorrectly pinned it to linux-musl

This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "/app/node_modules/@prisma/client/runtime/libquery_engine-linux-musl.so.node")

Searched Locations:

  /app/node_modules/.prisma/client
  E:\Projects\servers\ahub-api\node_modules\@prisma\client
  /app/node_modules/@prisma/client
  /app/node_modules/.prisma/client
  /app/node_modules/.prisma/client
  /tmp/prisma-engines
  /app/node_modules/.prisma/client


To solve this problem, add the platform "linux-musl" to the "binaryTargets" attribute in the "generator" block in the "schema.prisma" file:
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native"]
}

Then run "prisma generate" for your changes to take effect.
Read more about deploying Prisma Client: https://pris.ly/d/client-generator
AHUB API:ERROR [Dec-07-2022 20:32:12] Error Connecting to Database: Error: Error in connector: Error creating a database connection. (An error occurred during DNS resolution: proto error: io error: Network unreachable (os error 101))
AHUB API:ERROR [Dec-07-2022 20:32:42] Error Connecting to Database: Error: Error in connector: Error creating a database connection. (An error occurred during DNS resolution: proto error: io error: Network unreachable (os error 101))
AHUB API:ERROR [Dec-07-2022 20:38:19] Error Connecting to Database: Error: Error in connector: Error creating a database connection. (An error occurred during DNS resolution: no record found for name: _mongodb._tcp.cluster0.qutaxg0.mongodb.net. type: SRV class: IN)
AHUB API:ERROR [Dec-07-2022 21:29:06] Error Connecting to Database: Error: Query engine library for current platform "linux-musl" could not be found.
You incorrectly pinned it to linux-musl

This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "/app/node_modules/@prisma/client/runtime/libquery_engine-linux-musl.so.node")

Searched Locations:

  /app/node_modules/.prisma/client
  E:\Projects\servers\ahub-api\node_modules\@prisma\client
  /app/node_modules/@prisma/client
  /app/node_modules/.prisma/client
  /app/node_modules/.prisma/client
  /tmp/prisma-engines
  /app/node_modules/.prisma/client


To solve this problem, add the platform "linux-musl" to the "binaryTargets" attribute in the "generator" block in the "schema.prisma" file:
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native"]
}

Then run "prisma generate" for your changes to take effect.
Read more about deploying Prisma Client: https://pris.ly/d/client-generator
AHUB API:ERROR [Dec-07-2022 21:39:11] Error Connecting to Database: Error: Query engine library for current platform "linux-musl" could not be found.
You incorrectly pinned it to linux-musl

This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "/app/node_modules/@prisma/client/runtime/libquery_engine-linux-musl.so.node")

Searched Locations:

  /app/node_modules/.prisma/client
  E:\Projects\servers\ahub-api\node_modules\@prisma\client
  /app/node_modules/@prisma/client
  /app/node_modules/.prisma/client
  /app/node_modules/.prisma/client
  /tmp/prisma-engines
  /app/node_modules/.prisma/client


To solve this problem, add the platform "linux-musl" to the "binaryTargets" attribute in the "generator" block in the "schema.prisma" file:
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native"]
}

Then run "prisma generate" for your changes to take effect.
Read more about deploying Prisma Client: https://pris.ly/d/client-generator
AHUB API:ERROR [Dec-07-2022 23:12:07] Error Registering Patron : {}  ðŸ˜ 
AHUB API:ERROR [Dec-07-2022 23:13:01] Error Registering Patron : {}  ðŸ˜ 
AHUB API:ERROR [Dec-07-2022 23:17:37] Error Registering Patron : {}  ðŸ˜ 
AHUB API:ERROR [Dec-07-2022 23:19:03] Error Registering Patron : {}  ðŸ˜ 
AHUB API:ERROR [Dec-07-2022 23:19:36] Error Registering Patron : {}  ðŸ˜ 
AHUB API:ERROR [Dec-07-2022 23:21:03] Error Registering Patron : {}  ðŸ˜ 
AHUB API:ERROR [Dec-07-2022 23:21:45] Error Registering Patron : {}  ðŸ˜ 
AHUB API:ERROR [Dec-07-2022 23:26:04] Error Registering Patron : {"clientVersion":"4.6.1"}  ðŸ˜ 
AHUB API:ERROR [Dec-07-2022 23:28:46] Error Registering Patron : {"code":"P2009","clientVersion":"4.6.1","meta":{"query_validation_error":"Unable to match input value to any allowed input type for the field. Parse errors: [Query parsing/validation error at `Mutation.createOneUser.data.UserCreateInput.Role`: A value is required but not set., Query parsing/validation error at `Mutation.createOneUser.data.UserUncheckedCreateInput.password`: A value is required but not set.]","query_position":"Mutation.createOneUser.data"}}  ðŸ˜ 
AHUB API:ERROR [Dec-07-2022 22:48:55] Error Connecting to Database: Error: Error in connector: Error creating a database connection. (An error occurred during DNS resolution: no record found for name: _mongodb._tcp.cluster0.qutaxg0.mongodb.net. type: SRV class: IN)
AHUB API:ERROR [Dec-07-2022 22:52:53] Error Connecting to Database: Error: Query engine library for current platform "linux-musl" could not be found.
You incorrectly pinned it to linux-musl

This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "/app/node_modules/@prisma/client/runtime/libquery_engine-linux-musl.so.node")

Searched Locations:

  /app/node_modules/.prisma/client
  E:\Projects\servers\ahub-api\node_modules\@prisma\client
  /app/node_modules/@prisma/client
  /app/node_modules/.prisma/client
  /app/node_modules/.prisma/client
  /tmp/prisma-engines
  /app/node_modules/.prisma/client


To solve this problem, add the platform "linux-musl" to the "binaryTargets" attribute in the "generator" block in the "schema.prisma" file:
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native"]
}

Then run "prisma generate" for your changes to take effect.
Read more about deploying Prisma Client: https://pris.ly/d/client-generator
AHUB API:ERROR [Dec-07-2022 23:39:55] Error Connecting to Database: Error: Query engine library for current platform "linux-musl" could not be found.
You incorrectly pinned it to linux-musl

This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "/app/node_modules/@prisma/client/runtime/libquery_engine-linux-musl.so.node")

Searched Locations:

  /app/node_modules/.prisma/client
  E:\Projects\servers\ahub-api\node_modules\@prisma\client
  /app/node_modules/@prisma/client
  /app/node_modules/.prisma/client
  /app/node_modules/.prisma/client
  /tmp/prisma-engines
  /app/node_modules/.prisma/client


To solve this problem, add the platform "linux-musl" to the "binaryTargets" attribute in the "generator" block in the "schema.prisma" file:
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native"]
}

Then run "prisma generate" for your changes to take effect.
Read more about deploying Prisma Client: https://pris.ly/d/client-generator
AHUB API:ERROR [Dec-08-2022 01:57:06] Error Registering Patron : {"message":"Request failed with status code 422","name":"AxiosError","stack":"AxiosError: Request failed with status code 422\n    at settle (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:1855:12)\n    at IncomingMessage.handleStreamEnd (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2712:11)\n    at IncomingMessage.emit (node:events:532:35)\n    at endReadableNT (node:internal/streams/readable:1346:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/1.2.1","Content-Length":"203","Accept-Encoding":"gzip, compress, deflate, br"},"baseURL":"https://api.ng.termii.com/api","method":"post","url":"/sms/send","data":"{\"type\":\"plain\",\"channel\":\"6391365dbd2c3009d33d5fb9\",\"from\":\"A-HUB\",\"api_key\":\"TLG8sDszGNKIyduy30Oo0w2IFCVubBkwPkK652Bwo1YTL1hL0edFgM92KEbbdc\",\"to\":\"+2348034074748\",\"sms\":\"An OTP to verify your account\"}"},"code":"ERR_BAD_REQUEST","status":422}  ðŸ˜ 
AHUB API:ERROR [Dec-08-2022 02:00:59] Error Registering Patron : {"message":"Request failed with status code 400","name":"AxiosError","stack":"AxiosError: Request failed with status code 400\n    at settle (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:1855:12)\n    at IncomingMessage.handleStreamEnd (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2712:11)\n    at IncomingMessage.emit (node:events:532:35)\n    at endReadableNT (node:internal/streams/readable:1346:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/1.2.1","Content-Length":"201","Accept-Encoding":"gzip, compress, deflate, br"},"baseURL":"https://api.ng.termii.com/api","method":"post","url":"/sms/send","data":"{\"type\":\"plain\",\"channel\":\"dnd\",\"from\":\"A-HUB\",\"api_key\":\"TLG8sDszGNKIyduy30Oo0w2IFCVubBkwPkK652Bwo1YTL1hL0edFgM92KEbbdc\",\"to\":[\"2348034074748\"],\"sms\":\"An OTP to verify your account: [object Object].\"}"},"code":"ERR_BAD_REQUEST","status":400}  ðŸ˜ 
AHUB API:ERROR [Dec-08-2022 02:09:38] Error Registering Patron : {"message":"Request failed with status code 400","name":"AxiosError","stack":"AxiosError: Request failed with status code 400\n    at settle (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:1855:12)\n    at IncomingMessage.handleStreamEnd (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2712:11)\n    at IncomingMessage.emit (node:events:532:35)\n    at endReadableNT (node:internal/streams/readable:1346:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/1.2.1","Content-Length":"200","Accept-Encoding":"gzip, compress, deflate, br"},"baseURL":"https://api.ng.termii.com/api","method":"post","url":"/sms/send","data":"{\"type\":\"plain\",\"channel\":\"dnd\",\"from\":\"A-HUB\",\"api_key\":\"TLG8sDszGNKIyduy30Oo0w2IFCVubBkwPkK652Bwo1YTL1hL0edFgM92KEbbdc\",\"to\":[\"2348034074748\"],\"sms\":\"An OTP to verify your account: [object Object]\"}"},"code":"ERR_BAD_REQUEST","status":400}  ðŸ˜ 
AHUB API:ERROR [Dec-08-2022 02:13:21] Error Registering Patron : {"message":"Request failed with status code 400","name":"AxiosError","stack":"AxiosError: Request failed with status code 400\n    at settle (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:1855:12)\n    at IncomingMessage.handleStreamEnd (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2712:11)\n    at IncomingMessage.emit (node:events:532:35)\n    at endReadableNT (node:internal/streams/readable:1346:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/1.2.1","Content-Length":"200","Accept-Encoding":"gzip, compress, deflate, br"},"baseURL":"https://api.ng.termii.com/api","method":"post","url":"/sms/send","data":"{\"type\":\"plain\",\"channel\":\"dnd\",\"from\":\"A-HUB\",\"api_key\":\"TLG8sDszGNKIyduy30Oo0w2IFCVubBkwPkK652Bwo1YTL1hL0edFgM92KEbbdc\",\"to\":[\"2348034074748\"],\"sms\":\"An OTP to verify your account: [object Object]\"}"},"code":"ERR_BAD_REQUEST","status":400}  ðŸ˜ 
AHUB API:ERROR [Dec-08-2022 02:18:16] Error Registering Patron : {"message":"Request failed with status code 400","name":"AxiosError","stack":"AxiosError: Request failed with status code 400\n    at settle (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:1855:12)\n    at IncomingMessage.handleStreamEnd (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2712:11)\n    at IncomingMessage.emit (node:events:532:35)\n    at endReadableNT (node:internal/streams/readable:1346:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/1.2.1","Content-Length":"189","Accept-Encoding":"gzip, compress, deflate, br"},"baseURL":"https://api.ng.termii.com/api","method":"post","url":"/sms/send","data":"{\"type\":\"plain\",\"channel\":\"dnd\",\"from\":\"A-HUB\",\"api_key\":\"TLG8sDszGNKIyduy30Oo0w2IFCVubBkwPkK652Bwo1YTL1hL0edFgM92KEbbdc\",\"to\":[\"2348034074748\"],\"sms\":\"An OTP to verify your account: 9327\"}"},"code":"ERR_BAD_REQUEST","status":400}  ðŸ˜ 
AHUB API:ERROR [Dec-08-2022 02:24:03] Error Registering Patron : {"message":"Request failed with status code 400","name":"AxiosError","stack":"AxiosError: Request failed with status code 400\n    at settle (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:1855:12)\n    at IncomingMessage.handleStreamEnd (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2712:11)\n    at IncomingMessage.emit (node:events:532:35)\n    at endReadableNT (node:internal/streams/readable:1346:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/1.2.1","Content-Length":"189","Accept-Encoding":"gzip, compress, deflate, br"},"baseURL":"https://api.ng.termii.com/api","method":"post","url":"/sms/send","data":"{\"type\":\"plain\",\"channel\":\"dnd\",\"from\":\"A-HUB\",\"api_key\":\"TLG8sDszGNKIyduy30Oo0w2IFCVubBkwPkK652Bwo1YTL1hL0edFgM92KEbbdc\",\"to\":[\"2348034074748\"],\"sms\":\"An OTP to verify your account: 5418\"}"},"code":"ERR_BAD_REQUEST","status":400}  ðŸ˜ 
AHUB API:ERROR [Dec-08-2022 02:29:36] SMS Error: {"message":"Request failed with status code 400","name":"AxiosError","stack":"AxiosError: Request failed with status code 400\n    at settle (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:1855:12)\n    at IncomingMessage.handleStreamEnd (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2712:11)\n    at IncomingMessage.emit (node:events:532:35)\n    at endReadableNT (node:internal/streams/readable:1346:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/1.2.1","Content-Length":"189","Accept-Encoding":"gzip, compress, deflate, br"},"baseURL":"https://api.ng.termii.com/api","method":"post","url":"/sms/send","data":"{\"type\":\"plain\",\"channel\":\"dnd\",\"from\":\"A-HUB\",\"api_key\":\"TLG8sDszGNKIyduy30Oo0w2IFCVubBkwPkK652Bwo1YTL1hL0edFgM92KEbbdc\",\"to\":[\"2348034074748\"],\"sms\":\"An OTP to verify your account: 3511\"}"},"code":"ERR_BAD_REQUEST","status":400}
AHUB API:ERROR [Dec-08-2022 02:29:36] Error Registering Patron : {"message":"Request failed with status code 400","name":"AxiosError","stack":"AxiosError: Request failed with status code 400\n    at settle (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:1855:12)\n    at IncomingMessage.handleStreamEnd (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2712:11)\n    at IncomingMessage.emit (node:events:532:35)\n    at endReadableNT (node:internal/streams/readable:1346:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/1.2.1","Content-Length":"189","Accept-Encoding":"gzip, compress, deflate, br"},"baseURL":"https://api.ng.termii.com/api","method":"post","url":"/sms/send","data":"{\"type\":\"plain\",\"channel\":\"dnd\",\"from\":\"A-HUB\",\"api_key\":\"TLG8sDszGNKIyduy30Oo0w2IFCVubBkwPkK652Bwo1YTL1hL0edFgM92KEbbdc\",\"to\":[\"2348034074748\"],\"sms\":\"An OTP to verify your account: 3511\"}"},"code":"ERR_BAD_REQUEST","status":400}  ðŸ˜ 
AHUB API:ERROR [Dec-08-2022 02:35:39] SMS Error: {"message":"Request failed with status code 400","name":"AxiosError","stack":"AxiosError: Request failed with status code 400\n    at settle (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:1855:12)\n    at IncomingMessage.handleStreamEnd (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2712:11)\n    at IncomingMessage.emit (node:events:532:35)\n    at endReadableNT (node:internal/streams/readable:1346:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/1.2.1","Content-Length":"189","Accept-Encoding":"gzip, compress, deflate, br"},"baseURL":"https://api.ng.termii.com/api","method":"post","url":"/sms/send","data":"{\"to\":[\"2348034074748\"],\"from\":\"A-HUB\",\"sms\":\"An OTP to verify your account: 0955\",\"type\":\"plain\",\"api_key\":\"TLG8sDszGNKIyduy30Oo0w2IFCVubBkwPkK652Bwo1YTL1hL0edFgM92KEbbdc\",\"channel\":\"dnd\"}"},"code":"ERR_BAD_REQUEST","status":400}
AHUB API:ERROR [Dec-08-2022 02:35:39] Error Registering Patron : {"message":"Request failed with status code 400","name":"AxiosError","stack":"AxiosError: Request failed with status code 400\n    at settle (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:1855:12)\n    at IncomingMessage.handleStreamEnd (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2712:11)\n    at IncomingMessage.emit (node:events:532:35)\n    at endReadableNT (node:internal/streams/readable:1346:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/1.2.1","Content-Length":"189","Accept-Encoding":"gzip, compress, deflate, br"},"baseURL":"https://api.ng.termii.com/api","method":"post","url":"/sms/send","data":"{\"to\":[\"2348034074748\"],\"from\":\"A-HUB\",\"sms\":\"An OTP to verify your account: 0955\",\"type\":\"plain\",\"api_key\":\"TLG8sDszGNKIyduy30Oo0w2IFCVubBkwPkK652Bwo1YTL1hL0edFgM92KEbbdc\",\"channel\":\"dnd\"}"},"code":"ERR_BAD_REQUEST","status":400}  ðŸ˜ 
AHUB API:ERROR [Dec-08-2022 02:41:40] SMS Error: {"message":"Request failed with status code 400","name":"AxiosError","stack":"AxiosError: Request failed with status code 400\n    at settle (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:1855:12)\n    at IncomingMessage.handleStreamEnd (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2712:11)\n    at IncomingMessage.emit (node:events:532:35)\n    at endReadableNT (node:internal/streams/readable:1346:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/1.2.1","Content-Length":"193","Accept-Encoding":"gzip, compress, deflate, br"},"baseURL":"https://api.ng.termii.com/api","method":"post","url":"/sms/send","data":"{\"type\":\"plain\",\"channel\":\"dnd\",\"from\":\"ahub21457\",\"api_key\":\"TLG8sDszGNKIyduy30Oo0w2IFCVubBkwPkK652Bwo1YTL1hL0edFgM92KEbbdc\",\"to\":[\"2348034074748\"],\"sms\":\"An OTP to verify your account: 2745\"}"},"code":"ERR_BAD_REQUEST","status":400}
AHUB API:ERROR [Dec-08-2022 02:41:40] Error Registering Patron : {"message":"Request failed with status code 400","name":"AxiosError","stack":"AxiosError: Request failed with status code 400\n    at settle (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:1855:12)\n    at IncomingMessage.handleStreamEnd (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2712:11)\n    at IncomingMessage.emit (node:events:532:35)\n    at endReadableNT (node:internal/streams/readable:1346:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/1.2.1","Content-Length":"193","Accept-Encoding":"gzip, compress, deflate, br"},"baseURL":"https://api.ng.termii.com/api","method":"post","url":"/sms/send","data":"{\"type\":\"plain\",\"channel\":\"dnd\",\"from\":\"ahub21457\",\"api_key\":\"TLG8sDszGNKIyduy30Oo0w2IFCVubBkwPkK652Bwo1YTL1hL0edFgM92KEbbdc\",\"to\":[\"2348034074748\"],\"sms\":\"An OTP to verify your account: 2745\"}"},"code":"ERR_BAD_REQUEST","status":400}  ðŸ˜ 
AHUB API:ERROR [Dec-08-2022 03:11:53] SMS Error: {"message":"Request failed with status code 400","name":"AxiosError","stack":"AxiosError: Request failed with status code 400\n    at settle (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:1855:12)\n    at IncomingMessage.handleStreamEnd (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2712:11)\n    at IncomingMessage.emit (node:events:532:35)\n    at endReadableNT (node:internal/streams/readable:1346:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/1.2.1","Content-Length":"189","Accept-Encoding":"gzip, compress, deflate, br"},"baseURL":"https://api.ng.termii.com/api","method":"post","url":"/sms/send","data":"{\"type\":\"plain\",\"channel\":\"dnd\",\"from\":\"A-HUB\",\"api_key\":\"TLG8sDszGNKIyduy30Oo0w2IFCVubBkwPkK652Bwo1YTL1hL0edFgM92KEbbdc\",\"to\":[\"2348034074748\"],\"sms\":\"An OTP to verify your account: 3826\"}"},"code":"ERR_BAD_REQUEST","status":400}
AHUB API:ERROR [Dec-08-2022 03:11:53] Error Registering Patron : {"message":"Request failed with status code 400","name":"AxiosError","stack":"AxiosError: Request failed with status code 400\n    at settle (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:1855:12)\n    at IncomingMessage.handleStreamEnd (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2712:11)\n    at IncomingMessage.emit (node:events:532:35)\n    at endReadableNT (node:internal/streams/readable:1346:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/1.2.1","Content-Length":"189","Accept-Encoding":"gzip, compress, deflate, br"},"baseURL":"https://api.ng.termii.com/api","method":"post","url":"/sms/send","data":"{\"type\":\"plain\",\"channel\":\"dnd\",\"from\":\"A-HUB\",\"api_key\":\"TLG8sDszGNKIyduy30Oo0w2IFCVubBkwPkK652Bwo1YTL1hL0edFgM92KEbbdc\",\"to\":[\"2348034074748\"],\"sms\":\"An OTP to verify your account: 3826\"}"},"code":"ERR_BAD_REQUEST","status":400}  ðŸ˜ 
AHUB API:ERROR [Dec-09-2022 07:02:25] Error Registering Patron : {"errno":-3001,"code":"EDNS","syscall":"getaddrinfo","hostname":"smtp.zoho.com","command":"CONN"}  ðŸ˜ 
AHUB API:ERROR [Dec-09-2022 07:08:37] Error Registering Patron : {"errno":-3001,"code":"EDNS","syscall":"getaddrinfo","hostname":"smtp.zoho.com","command":"CONN"}  ðŸ˜ 
AHUB API:ERROR [Dec-09-2022 14:59:05] Error Connecting to Database: Error: Error in connector: Error creating a database connection. (An error occurred during DNS resolution: proto error: io error: A socket operation was attempted to an unreachable network. (os error 10051))
AHUB API:ERROR [Dec-09-2022 15:07:17] Error Connecting to Database: Error: Error in connector: Error creating a database connection. (An error occurred during DNS resolution: proto error: io error: A socket operation was attempted to an unreachable network. (os error 10051))
AHUB API:ERROR [Dec-09-2022 22:13:21] SMS Error: {"message":"getaddrinfo EAI_AGAIN api.ng.termii.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN api.ng.termii.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:785:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2733:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/1.2.1","Content-Length":"189","Accept-Encoding":"gzip, compress, deflate, br"},"baseURL":"https://api.ng.termii.com/api","method":"post","url":"/sms/send","data":"{\"type\":\"plain\",\"channel\":\"dnd\",\"from\":\"A-HUB\",\"api_key\":\"TLG8sDszGNKIyduy30Oo0w2IFCVubBkwPkK652Bwo1YTL1hL0edFgM92KEbbdc\",\"to\":[\"2348034074748\"],\"sms\":\"An OTP to verify your account: 2072\"}"},"code":"EAI_AGAIN","status":null}
AHUB API:ERROR [Dec-09-2022 22:13:21] Error Registering Patron : {"message":"getaddrinfo EAI_AGAIN api.ng.termii.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN api.ng.termii.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:785:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2733:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/1.2.1","Content-Length":"189","Accept-Encoding":"gzip, compress, deflate, br"},"baseURL":"https://api.ng.termii.com/api","method":"post","url":"/sms/send","data":"{\"type\":\"plain\",\"channel\":\"dnd\",\"from\":\"A-HUB\",\"api_key\":\"TLG8sDszGNKIyduy30Oo0w2IFCVubBkwPkK652Bwo1YTL1hL0edFgM92KEbbdc\",\"to\":[\"2348034074748\"],\"sms\":\"An OTP to verify your account: 2072\"}"},"code":"EAI_AGAIN","status":null}  ðŸ˜ 
AHUB API:ERROR [Dec-09-2022 22:16:17] Login failed. Please try again later.: Error: 
Invalid `prisma_1.Prisma.user.findUnique()` invocation in
E:\Projects\servers\ahub-api\dist\Controllers\AuthController.js:34:61

  31 try {
  32     //const data = await Cache.baseCache('login', async () => {
  33     Libs_1.Logger.info('Signing In.....');
â†’ 34     const user = yield prisma_1.Prisma.user.findUnique(
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: RawDatabaseError { code: "unknown", message: "An existing connection was forcibly closed by the remote host. (os error 10054)" } })
AHUB API:ERROR [Dec-09-2022 22:16:47] Login failed. Please try again later.: Error: Invalid login credentials
AHUB API:ERROR [Dec-09-2022 22:17:09] SMS Error: {"message":"getaddrinfo EAI_AGAIN api.ng.termii.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN api.ng.termii.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:785:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2733:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/1.2.1","Content-Length":"189","Accept-Encoding":"gzip, compress, deflate, br"},"baseURL":"https://api.ng.termii.com/api","method":"post","url":"/sms/send","data":"{\"type\":\"plain\",\"channel\":\"dnd\",\"from\":\"A-HUB\",\"api_key\":\"TLG8sDszGNKIyduy30Oo0w2IFCVubBkwPkK652Bwo1YTL1hL0edFgM92KEbbdc\",\"to\":[\"2348034074748\"],\"sms\":\"An OTP to verify your account: 8780\"}"},"code":"EAI_AGAIN","status":null}
AHUB API:ERROR [Dec-09-2022 22:17:09] Error Registering Patron : {"message":"getaddrinfo EAI_AGAIN api.ng.termii.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN api.ng.termii.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:785:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2733:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/1.2.1","Content-Length":"189","Accept-Encoding":"gzip, compress, deflate, br"},"baseURL":"https://api.ng.termii.com/api","method":"post","url":"/sms/send","data":"{\"type\":\"plain\",\"channel\":\"dnd\",\"from\":\"A-HUB\",\"api_key\":\"TLG8sDszGNKIyduy30Oo0w2IFCVubBkwPkK652Bwo1YTL1hL0edFgM92KEbbdc\",\"to\":[\"2348034074748\"],\"sms\":\"An OTP to verify your account: 8780\"}"},"code":"EAI_AGAIN","status":null}  ðŸ˜ 
AHUB API:ERROR [Dec-09-2022 22:21:24] Error adding task: Error: 
Invalid `prisma_1.Prisma.task.create()` invocation in
E:\Projects\servers\ahub-api\dist\Services\TaskService.js:18:61

  15 return __awaiter(this, void 0, void 0, function* () {
  16     return new Promise((resolve, reject) => __awaiter(this, void 0, void 0, function* () {
  17         try {
â†’ 18             const task = yield prisma_1.Prisma.task.create({
                   data: {
                     name: 'item name',
                     type: 'Percel',
                     amount: '1000',
                             ~~~~~~
                     weightKg: '5',
                     ~~~~~~~~
                     is_fragile: 'true',
                                 ~~~~~~
                     note: 'my head phone',
                     recipient_name: 'Hassan',
                     recipient_phone: '+2348034074748',
                     pick_up: '',
                     drop_off: '',
                     patron_id: '6393a5d1641ddf4145da9530'
                   }
                 })

Argument amount: Got invalid value '1000' on prisma.createOneTask. Provided String, expected Float.
Unknown arg `weightKg` in data.weightKg for type TaskUncheckedCreateInput. Did you mean `weigtKg`? Available args:
type TaskUncheckedCreateInput {
  id?: String
  name?: String | Null
  type?: ItemType | Null
  amount?: Float
  note?: String | Null
  is_fragile?: Boolean
  weigtKg?: Float
  recipient_name?: String | Null
  recipient_phone: String
  pick_up: Json
  drop_off: Json
  patron_id: String
}
Argument is_fragile: Got invalid value 'true' on prisma.createOneTask. Provided String, expected Boolean.


AHUB API:ERROR [Dec-09-2022 22:24:41] Error adding task: Error: 
Invalid `prisma_1.Prisma.task.create()` invocation in
E:\Projects\servers\ahub-api\dist\Services\TaskService.js:18:61

  15 return __awaiter(this, void 0, void 0, function* () {
  16     return new Promise((resolve, reject) => __awaiter(this, void 0, void 0, function* () {
  17         try {
â†’ 18             const task = yield prisma_1.Prisma.task.create({
                   data: {
                     name: 'item name',
                     type: 'Percel',
                     amount: '1000',
                             ~~~~~~
                     weightKg: '5',
                     ~~~~~~~~
                     is_fragile: true,
                     note: 'my head phone',
                     recipient_name: 'Hassan',
                     recipient_phone: '+2348034074748',
                     pick_up: '',
                     drop_off: '',
                     patron_id: '6393a5d1641ddf4145da9530'
                   }
                 })

Argument amount: Got invalid value '1000' on prisma.createOneTask. Provided String, expected Float.
Unknown arg `weightKg` in data.weightKg for type TaskUncheckedCreateInput. Did you mean `weigtKg`? Available args:
type TaskUncheckedCreateInput {
  id?: String
  name?: String | Null
  type?: ItemType | Null
  amount?: Float
  note?: String | Null
  is_fragile?: Boolean
  weigtKg?: Float
  recipient_name?: String | Null
  recipient_phone: String
  pick_up: Json
  drop_off: Json
  patron_id: String
}


AHUB API:ERROR [Dec-09-2022 22:27:20] Error adding task: Error: 
Invalid `prisma_1.Prisma.task.create()` invocation in
E:\Projects\servers\ahub-api\dist\Services\TaskService.js:18:61

  15 return __awaiter(this, void 0, void 0, function* () {
  16     return new Promise((resolve, reject) => __awaiter(this, void 0, void 0, function* () {
  17         try {
â†’ 18             const task = yield prisma_1.Prisma.task.create({
                   data: {
                     name: 'item name',
                     type: 'Percel',
                     amount: 1000,
                     weightKg: 5,
                     ~~~~~~~~
                     is_fragile: true,
                     note: 'my head phone',
                     recipient_name: 'Hassan',
                     recipient_phone: '+2348034074748',
                     pick_up: '',
                     drop_off: '',
                     patron_id: '6393a5d1641ddf4145da9530'
                   }
                 })

Unknown arg `weightKg` in data.weightKg for type TaskUncheckedCreateInput. Did you mean `weigtKg`? Available args:
type TaskUncheckedCreateInput {
  id?: String
  name?: String | Null
  type?: ItemType | Null
  amount?: Float
  note?: String | Null
  is_fragile?: Boolean
  weigtKg?: Float
  recipient_name?: String | Null
  recipient_phone: String
  pick_up: Json
  drop_off: Json
  patron_id: String
}


AHUB API:ERROR [Dec-09-2022 22:31:26] Error adding task: TypeError: Cannot read properties of undefined (reading 'setSuccess')
AHUB API:ERROR [Dec-09-2022 22:34:35] Error adding task: TypeError: Cannot read properties of undefined (reading 'setSuccess')
AHUB API:ERROR [Dec-09-2022 22:48:33] Error adding task: Error: 
Invalid `prisma_1.Prisma.task.create()` invocation in
E:\Projects\servers\ahub-api\dist\Services\TaskService.js:18:61

  15 return __awaiter(this, void 0, void 0, function* () {
  16     return new Promise((resolve, reject) => __awaiter(this, void 0, void 0, function* () {
  17         try {
â†’ 18             const task = yield prisma_1.Prisma.task.create({
                   data: {
                     name: 'item name',
                     type: 'Percel',
                     amount: 1000,
                     weightKg: 5,
                     is_fragile: true,
                     note: 'my head phone',
                     recipient_name: 'Hassan',
                     recipient_phone: '+2348034074748',
                     pick_up: '',
                     drop_off: '',
                     patron_id: '6393a5d1641ddf4145da9530',
                 +   taskAssignmentId: String,
                 ?   id?: String,
                 ?   task_assignments?: {
                 ?     create?: TaskAssignmentCreateWithoutTaskInput | TaskAssignmentCreateWithoutTaskInput | TaskAssignmentUncheckedCreateWithoutTaskInput | TaskAssignmentUncheckedCreateWithoutTaskInput,
                 ?     connectOrCreate?: TaskAssignmentCreateOrConnectWithoutTaskInput | TaskAssignmentCreateOrConnectWithoutTaskInput,
                 ?     createMany?: TaskAssignmentCreateManyTaskInputEnvelope,
                 ?     connect?: TaskAssignmentWhereUniqueInput | TaskAssignmentWhereUniqueInput
                 ?   }
                   }
                 })

Argument taskAssignmentId for data.taskAssignmentId is missing.

Note: Lines with + are required, lines with ? are optional.

AHUB API:ERROR [Dec-09-2022 23:00:42] SMS Error: {"message":"getaddrinfo EAI_AGAIN api.ng.termii.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN api.ng.termii.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:785:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2733:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/1.2.1","Content-Length":"189","Accept-Encoding":"gzip, compress, deflate, br"},"baseURL":"https://api.ng.termii.com/api","method":"post","url":"/sms/send","data":"{\"type\":\"plain\",\"channel\":\"dnd\",\"from\":\"A-HUB\",\"api_key\":\"TLG8sDszGNKIyduy30Oo0w2IFCVubBkwPkK652Bwo1YTL1hL0edFgM92KEbbdc\",\"to\":[\"2348034074748\"],\"sms\":\"An OTP to verify your account: 6284\"}"},"code":"EAI_AGAIN","status":null}
AHUB API:ERROR [Dec-09-2022 23:00:42] Error Registering Artisan : {"message":"getaddrinfo EAI_AGAIN api.ng.termii.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN api.ng.termii.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:785:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2733:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/1.2.1","Content-Length":"189","Accept-Encoding":"gzip, compress, deflate, br"},"baseURL":"https://api.ng.termii.com/api","method":"post","url":"/sms/send","data":"{\"type\":\"plain\",\"channel\":\"dnd\",\"from\":\"A-HUB\",\"api_key\":\"TLG8sDszGNKIyduy30Oo0w2IFCVubBkwPkK652Bwo1YTL1hL0edFgM92KEbbdc\",\"to\":[\"2348034074748\"],\"sms\":\"An OTP to verify your account: 6284\"}"},"code":"EAI_AGAIN","status":null}  ðŸ˜ 
AHUB API:ERROR [Dec-16-2022 15:40:26] Error Generating Zoho Access And Refresh Token: {"clientVersion":"4.6.1"}
AHUB API:ERROR [Dec-16-2022 15:41:24] Error Generating Zoho Access And Refresh Token: {"clientVersion":"4.6.1"}
AHUB API:ERROR [Dec-16-2022 15:42:34] Error Generating Zoho Access And Refresh Token: {"clientVersion":"4.6.1"}
AHUB API:ERROR [Dec-16-2022 15:44:51] Error Generating Zoho Access And Refresh Token: {"clientVersion":"4.6.1"}
AHUB API:ERROR [Dec-16-2022 15:46:04] Error Generating Zoho Access And Refresh Token: {"clientVersion":"4.6.1"}
AHUB API:ERROR [Dec-16-2022 15:46:22] Error Generating Zoho Access And Refresh Token: {"clientVersion":"4.6.1"}
AHUB API:ERROR [Dec-16-2022 15:46:27] Error Generating Zoho Access And Refresh Token: {"clientVersion":"4.6.1"}
AHUB API:ERROR [Dec-16-2022 15:46:33] Error Generating Zoho Access And Refresh Token: {"clientVersion":"4.6.1"}
AHUB API:ERROR [Dec-16-2022 15:48:28] Error Generating Zoho Access And Refresh Token: {"clientVersion":"4.6.1"}
AHUB API:ERROR [Dec-16-2022 15:53:33] Error Generating Zoho Access And Refresh Token: {"clientVersion":"4.6.1"}
AHUB API:ERROR [Dec-16-2022 15:54:33] Error Generating Zoho Access And Refresh Token: {"clientVersion":"4.6.1"}
AHUB API:ERROR [Dec-16-2022 15:54:38] Error Generating Zoho Access And Refresh Token: {"clientVersion":"4.6.1"}
AHUB API:ERROR [Dec-16-2022 15:55:23] Error Generating Zoho Access And Refresh Token: {"clientVersion":"4.6.1"}
AHUB API:ERROR [Dec-16-2022 15:55:26] Error Generating Zoho Access And Refresh Token: {"clientVersion":"4.6.1"}
AHUB API:ERROR [Dec-16-2022 15:55:28] Error Generating Zoho Access And Refresh Token: {"clientVersion":"4.6.1"}
AHUB API:ERROR [Dec-16-2022 15:57:33] Error Generating Zoho Access And Refresh Token: {"clientVersion":"4.6.1"}
AHUB API:ERROR [Dec-16-2022 15:59:30] Error Generating Zoho Access And Refresh Token: {"clientVersion":"4.6.1"}
AHUB API:ERROR [Dec-16-2022 16:00:50] Error Generating Zoho Access And Refresh Token: {"clientVersion":"4.6.1"}
AHUB API:ERROR [Dec-16-2022 16:02:03] Error Generating Zoho Access And Refresh Token: {"clientVersion":"4.6.1"}
AHUB API:ERROR [Dec-16-2022 16:09:31] Error Generating Zoho Access And Refresh Token: {"clientVersion":"4.6.1"}
AHUB API:ERROR [Dec-16-2022 16:43:48] Error Generating Zoho Access And Refresh Token: {"message":"getaddrinfo EAI_AGAIN accounts.zoho.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN accounts.zoho.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:785:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2733:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded","User-Agent":"axios/1.2.1","Accept-Encoding":"gzip, compress, deflate, br"},"method":"post","url":"https://accounts.zoho.com/oauth/v2/token?client_id=1000.7GUE89PYTLT0GFBOSKU6KZLWVY62RR&client_secret=a408c7554618e22303e59a292e82e72c315de5b665&grant_type=authorization_code&code=1000.9c52390992c3935edc6f8b21427d68ca.8d4a3b766483c8d0c125424315ac3454"},"code":"EAI_AGAIN","status":null}
AHUB API:ERROR [Dec-16-2022 16:44:09] Error Generating Zoho Access And Refresh Token: {"clientVersion":"4.6.1"}
AHUB API:ERROR [Dec-16-2022 16:59:15] Error Generating Zoho Access And Refresh Token: {"clientVersion":"4.6.1"}
AHUB API:ERROR [Dec-16-2022 16:59:25] Error Generating Zoho Access And Refresh Token: {"clientVersion":"4.6.1"}
AHUB API:ERROR [Dec-16-2022 16:59:27] Error Generating Zoho Access And Refresh Token: {"clientVersion":"4.6.1"}
AHUB API:ERROR [Dec-16-2022 17:00:48] Error Generating Zoho Access And Refresh Token: {"clientVersion":"4.6.1"}
AHUB API:ERROR [Dec-16-2022 17:01:01] Error Generating Zoho Access And Refresh Token: {"clientVersion":"4.6.1"}
AHUB API:ERROR [Dec-16-2022 17:50:42] Error Creating Zoho Ticket: {"errorCode":"UNPROCESSABLE_ENTITY","message":"An extra parameter 'LastName' is found"}
AHUB API:ERROR [Dec-16-2022 17:51:12] Error Creating Zoho Ticket: {"errorCode":"INVALID_OAUTH","message":"The OAuth Token you provided is invalid."}
AHUB API:ERROR [Dec-16-2022 17:58:00] Error Creating Zoho Ticket: {"errorCode":"INVALID_DATA","message":"The data is invalid due to validation restrictions","errors":[{"fieldName":"/departmentId","errorType":"missing","errorMessage":""}]}
AHUB API:ERROR [Dec-16-2022 18:46:35] Error Generating Zoho Code: Error: 
Invalid `prisma_1.Prisma.zohoToken.update()` invocation in
E:\Projects\servers\ahub-api\dist\Services\ZohoService.js:71:65

  68 Libs_1.Logger.info('Refreshing Token');
  69 const { data } = yield Axios.post(`https://accounts.zoho.com/oauth/v2/token?client_id=${config_1.zohoCrmConfig.clientID}&client_secret=${config_1.zohoCrmConfig.clientSecret}&grant_type=refresh_token&refresh_token=${refresh_token}&scope=${config_1.zohoCrmConfig.scope}`);
  70 data.expires_in = addMinutes();
â†’ 71 const updated = yield prisma_1.Prisma.zohoToken.update({
       where: {
         id: '639ca03111f43a1124787cb6'
       },
       data: {
         access_token: '1000.75e7e631d49d1efcfe3ab0718f80048b.b2934c87f2816d14861dc6025dbea342',
         scope: 'Desk.tickets.ALL',
         ~~~~~
         api_domain: 'https://www.zohoapis.com',
         ~~~~~~~~~~
         token_type: 'Bearer',
         ~~~~~~~~~~
         expires_in: {
           _isAMomentObject: true,
           ~~~~~~~~~~~~~~~~
           _isUTC: false,
           ~~~~~~
           _pf: {
           ~~~
             empty: false,
             unusedTokens: [],
             unusedInput: [],
             overflow: -2,
             charsLeftOver: 0,
             nullInput: false,
             invalidEra: null,
             invalidMonth: null,
             invalidFormat: false,
             userInvalidated: false,
             iso: false,
             parsedDateParts: [],
             era: null,
             meridiem: null,
             rfc2822: false,
             weekdayMismatch: false
           },
           _locale: {
           ~~~~~~~
             _calendar: {
               sameDay: '[Today at] LT',
               nextDay: '[Tomorrow at] LT',
               nextWeek: 'dddd [at] LT',
               lastDay: '[Yesterday at] LT',
               lastWeek: '[Last] dddd [at] LT',
               sameElse: 'L'
             },
             _longDateFormat: {
               LTS: 'h:mm:ss A',
               LT: 'h:mm A',
               L: 'MM/DD/YYYY',
               LL: 'MMMM D, YYYY',
               LLL: 'MMMM D, YYYY h:mm A',
               LLLL: 'dddd, MMMM D, YYYY h:mm A'
             },
             _invalidDate: 'Invalid date',
             ordinal: function (number) {
                 var b = number % 10,
                     output =
                         toInt((number % 100) / 10) === 1
                             ? 'th'
                             : b === 1
                             ? 'st'
                             : b === 2
                             ? 'nd'
                             : b === 3
                             ? 'rd'
                             : 'th';
                 return number + output;
             },
             _dayOfMonthOrdinalParse: /\d{1,2}(th|st|nd|rd)/,
             _relativeTime: {
               future: 'in %s',
               past: '%s ago',
               s: 'a few seconds',
               ss: '%d seconds',
               m: 'a minute',
               mm: '%d minutes',
               h: 'an hour',
               hh: '%d hours',
               d: 'a day',
               dd: '%d days',
               w: 'a week',
               ww: '%d weeks',
               M: 'a month',
               MM: '%d months',
               y: 'a year',
               yy: '%d years'
             },
             _months: [
               'January',
               'February',
               'March',
               'April',
               'May',
               'June',
               'July',
               'August',
               'September',
               'October',
               'November',
               'December'
             ],
             _monthsShort: [
               'Jan',
               'Feb',
               'Mar',
               'Apr',
               'May',
               'Jun',
               'Jul',
               'Aug',
               'Sep',
               'Oct',
               'Nov',
               'Dec'
             ],
             _week: {
               dow: 0,
               doy: 6
             },
             _weekdays: [
               'Sunday',
               'Monday',
               'Tuesday',
               'Wednesday',
               'Thursday',
               'Friday',
               'Saturday'
             ],
             _weekdaysMin: [
               'Su',
               'Mo',
               'Tu',
               'We',
               'Th',
               'Fr',
               'Sa'
             ],
             _weekdaysShort: [
               'Sun',
               'Mon',
               'Tue',
               'Wed',
               'Thu',
               'Fri',
               'Sat'
             ],
             _meridiemParse: /[ap]\.?m?\.?/i,
             _eras: [
               {
                 since: '0001-01-01',
                 until: Infinity,
                 offset: 1,
                 name: 'Anno Domini',
                 narrow: 'AD',
                 abbr: 'AD'
               },
               {
                 since: '0000-12-31',
                 until: -Infinity,
                 offset: 1,
                 name: 'Before Christ',
                 narrow: 'BC',
                 abbr: 'BC'
               }
             ],
             _abbr: 'en',
             _config: {
               calendar: {
                 sameDay: '[Today at] LT',
                 nextDay: '[Tomorrow at] LT',
                 nextWeek: 'dddd [at] LT',
                 lastDay: '[Yesterday at] LT',
                 lastWeek: '[Last] dddd [at] LT',
                 sameElse: 'L'
               },
               longDateFormat: {
                 LTS: 'h:mm:ss A',
                 LT: 'h:mm A',
                 L: 'MM/DD/YYYY',
                 LL: 'MMMM D, YYYY',
                 LLL: 'MMMM D, YYYY h:mm A',
                 LLLL: 'dddd, MMMM D, YYYY h:mm A'
               },
               invalidDate: 'Invalid date',
               ordinal: function (number) {
                 var b = number % 10,
                     output =
                         toInt((number % 100) / 10) === 1
                             ? 'th'
                             : b === 1
                             ? 'st'
                             : b === 2
                             ? 'nd'
                             : b === 3
                             ? 'rd'
                             : 'th';
                 return number + output;
             },
               dayOfMonthOrdinalParse: /\d{1,2}(th|st|nd|rd)/,
               relativeTime: {
                 future: 'in %s',
                 past: '%s ago',
                 s: 'a few seconds',
                 ss: '%d seconds',
                 m: 'a minute',
                 mm: '%d minutes',
                 h: 'an hour',
                 hh: '%d hours',
                 d: 'a day',
                 dd: '%d days',
                 w: 'a week',
                 ww: '%d weeks',
                 M: 'a month',
                 MM: '%d months',
                 y: 'a year',
                 yy: '%d years'
               },
               months: [
                 'January',
                 'February',
                 'March',
                 'April',
                 'May',
                 'June',
                 'July',
                 'August',
                 'September',
                 'October',
                 'November',
                 'December'
               ],
               monthsShort: [
                 'Jan',
                 'Feb',
                 'Mar',
                 'Apr',
                 'May',
                 'Jun',
                 'Jul',
                 'Aug',
                 'Sep',
                 'Oct',
                 'Nov',
                 'Dec'
               ],
               week: {
                 dow: 0,
                 doy: 6
               },
               weekdays: [
                 'Sunday',
                 'Monday',
                 'Tuesday',
                 'Wednesday',
                 'Thursday',
                 'Friday',
                 'Saturday'
               ],
               weekdaysMin: [
                 'Su',
                 'Mo',
                 'Tu',
                 'We',
                 'Th',
                 'Fr',
                 'Sa'
               ],
               weekdaysShort: [
                 'Sun',
                 'Mon',
                 'Tue',
                 'Wed',
                 'Thu',
                 'Fri',
                 'Sat'
               ],
               meridiemParse: /[ap]\.?m?\.?/i,
               eras: [
                 {
                   since: '0001-01-01',
                   until: Infinity,
                   offset: 1,
                   name: 'Anno Domini',
                   narrow: 'AD',
                   abbr: 'AD'
                 },
                 {
                   since: '0000-12-31',
                   until: -Infinity,
                   offset: 1,
                   name: 'Before Christ',
                   narrow: 'BC',
                   abbr: 'BC'
                 }
               ],
               abbr: 'en'
             },
             _dayOfMonthOrdinalParseLenient: /\d{1,2}(th|st|nd|rd)|\d{1,2}/
           },
           _d: new Date('2022-12-16T18:41:35.365Z'),
           ~~
           _isValid: true
           ~~~~~~~~
         }
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       }
     })

Unknown arg `scope` in data.scope for type ZohoTokenUpdateInput. Did you mean `select`? Available args:
type ZohoTokenUpdateInput {
  access_token?: String | StringFieldUpdateOperationsInput
  refresh_token?: String | StringFieldUpdateOperationsInput
  expires_in?: String | StringFieldUpdateOperationsInput
}
Unknown arg `api_domain` in data.api_domain for type ZohoTokenUpdateInput. Did you mean `expires_in`? Available args:
type ZohoTokenUpdateInput {
  access_token?: String | StringFieldUpdateOperationsInput
  refresh_token?: String | StringFieldUpdateOperationsInput
  expires_in?: String | StringFieldUpdateOperationsInput
}
Unknown arg `token_type` in data.token_type for type ZohoTokenUpdateInput. Did you mean `access_token`? Available args:
type ZohoTokenUpdateInput {
  access_token?: String | StringFieldUpdateOperationsInput
  refresh_token?: String | StringFieldUpdateOperationsInput
  expires_in?: String | StringFieldUpdateOperationsInput
}
Argument data.expires_in of type StringFieldUpdateOperationsInput needs exactly one argument, but you provided _isAMomentObject and _isUTC and _pf and _locale and _d and _isValid. Please choose one. Available args: 
type StringFieldUpdateOperationsInput {
  set?: String
}
Unknown arg `_isAMomentObject` in data.expires_in._isAMomentObject for type StringFieldUpdateOperationsInput. Available args:

type StringFieldUpdateOperationsInput {
  set?: String
}
Unknown arg `_isUTC` in data.expires_in._isUTC for type StringFieldUpdateOperationsInput. Did you mean `set`? Available args:
type StringFieldUpdateOperationsInput {
  set?: String
}
Unknown arg `_pf` in data.expires_in._pf for type StringFieldUpdateOperationsInput. Did you mean `set`? Available args:
type StringFieldUpdateOperationsInput {
  set?: String
}
Unknown arg `_locale` in data.expires_in._locale for type StringFieldUpdateOperationsInput. Did you mean `select`? Available args:
type StringFieldUpdateOperationsInput {
  set?: String
}
Unknown arg `_d` in data.expires_in._d for type StringFieldUpdateOperationsInput. Available args:

type StringFieldUpdateOperationsInput {
  set?: String
}
Unknown arg `_isValid` in data.expires_in._isValid for type StringFieldUpdateOperationsInput. Did you mean `set`? Available args:
type StringFieldUpdateOperationsInput {
  set?: String
}


AHUB API:ERROR [Dec-16-2022 18:51:43] Error Generating Zoho Code: Error: 
Invalid `prisma_1.Prisma.zohoToken.update()` invocation in
E:\Projects\servers\ahub-api\dist\Services\ZohoService.js:71:65

  68 Libs_1.Logger.info('Refreshing Token');
  69 const { data } = yield Axios.post(`https://accounts.zoho.com/oauth/v2/token?client_id=${config_1.zohoCrmConfig.clientID}&client_secret=${config_1.zohoCrmConfig.clientSecret}&grant_type=refresh_token&refresh_token=${refresh_token}&scope=${config_1.zohoCrmConfig.scope}`);
  70 data.expires_in = addMinutes();
â†’ 71 const updated = yield prisma_1.Prisma.zohoToken.update({
       where: {
         id: '639ca03111f43a1124787cb6'
       },
       data: {
         access_token: '1000.0160decaadaeddd9f4d2717832723fc9.74a462ba3210e593b9f85e004cb4e05f',
         scope: 'Desk.tickets.ALL',
         ~~~~~
         api_domain: 'https://www.zohoapis.com',
         ~~~~~~~~~~
         token_type: 'Bearer',
         ~~~~~~~~~~
         expires_in: {
           _isAMomentObject: true,
           ~~~~~~~~~~~~~~~~
           _isUTC: false,
           ~~~~~~
           _pf: {
           ~~~
             empty: false,
             unusedTokens: [],
             unusedInput: [],
             overflow: -2,
             charsLeftOver: 0,
             nullInput: false,
             invalidEra: null,
             invalidMonth: null,
             invalidFormat: false,
             userInvalidated: false,
             iso: false,
             parsedDateParts: [],
             era: null,
             meridiem: null,
             rfc2822: false,
             weekdayMismatch: false
           },
           _locale: {
           ~~~~~~~
             _calendar: {
               sameDay: '[Today at] LT',
               nextDay: '[Tomorrow at] LT',
               nextWeek: 'dddd [at] LT',
               lastDay: '[Yesterday at] LT',
               lastWeek: '[Last] dddd [at] LT',
               sameElse: 'L'
             },
             _longDateFormat: {
               LTS: 'h:mm:ss A',
               LT: 'h:mm A',
               L: 'MM/DD/YYYY',
               LL: 'MMMM D, YYYY',
               LLL: 'MMMM D, YYYY h:mm A',
               LLLL: 'dddd, MMMM D, YYYY h:mm A'
             },
             _invalidDate: 'Invalid date',
             ordinal: function (number) {
                 var b = number % 10,
                     output =
                         toInt((number % 100) / 10) === 1
                             ? 'th'
                             : b === 1
                             ? 'st'
                             : b === 2
                             ? 'nd'
                             : b === 3
                             ? 'rd'
                             : 'th';
                 return number + output;
             },
             _dayOfMonthOrdinalParse: /\d{1,2}(th|st|nd|rd)/,
             _relativeTime: {
               future: 'in %s',
               past: '%s ago',
               s: 'a few seconds',
               ss: '%d seconds',
               m: 'a minute',
               mm: '%d minutes',
               h: 'an hour',
               hh: '%d hours',
               d: 'a day',
               dd: '%d days',
               w: 'a week',
               ww: '%d weeks',
               M: 'a month',
               MM: '%d months',
               y: 'a year',
               yy: '%d years'
             },
             _months: [
               'January',
               'February',
               'March',
               'April',
               'May',
               'June',
               'July',
               'August',
               'September',
               'October',
               'November',
               'December'
             ],
             _monthsShort: [
               'Jan',
               'Feb',
               'Mar',
               'Apr',
               'May',
               'Jun',
               'Jul',
               'Aug',
               'Sep',
               'Oct',
               'Nov',
               'Dec'
             ],
             _week: {
               dow: 0,
               doy: 6
             },
             _weekdays: [
               'Sunday',
               'Monday',
               'Tuesday',
               'Wednesday',
               'Thursday',
               'Friday',
               'Saturday'
             ],
             _weekdaysMin: [
               'Su',
               'Mo',
               'Tu',
               'We',
               'Th',
               'Fr',
               'Sa'
             ],
             _weekdaysShort: [
               'Sun',
               'Mon',
               'Tue',
               'Wed',
               'Thu',
               'Fri',
               'Sat'
             ],
             _meridiemParse: /[ap]\.?m?\.?/i,
             _eras: [
               {
                 since: '0001-01-01',
                 until: Infinity,
                 offset: 1,
                 name: 'Anno Domini',
                 narrow: 'AD',
                 abbr: 'AD'
               },
               {
                 since: '0000-12-31',
                 until: -Infinity,
                 offset: 1,
                 name: 'Before Christ',
                 narrow: 'BC',
                 abbr: 'BC'
               }
             ],
             _abbr: 'en',
             _config: {
               calendar: {
                 sameDay: '[Today at] LT',
                 nextDay: '[Tomorrow at] LT',
                 nextWeek: 'dddd [at] LT',
                 lastDay: '[Yesterday at] LT',
                 lastWeek: '[Last] dddd [at] LT',
                 sameElse: 'L'
               },
               longDateFormat: {
                 LTS: 'h:mm:ss A',
                 LT: 'h:mm A',
                 L: 'MM/DD/YYYY',
                 LL: 'MMMM D, YYYY',
                 LLL: 'MMMM D, YYYY h:mm A',
                 LLLL: 'dddd, MMMM D, YYYY h:mm A'
               },
               invalidDate: 'Invalid date',
               ordinal: function (number) {
                 var b = number % 10,
                     output =
                         toInt((number % 100) / 10) === 1
                             ? 'th'
                             : b === 1
                             ? 'st'
                             : b === 2
                             ? 'nd'
                             : b === 3
                             ? 'rd'
                             : 'th';
                 return number + output;
             },
               dayOfMonthOrdinalParse: /\d{1,2}(th|st|nd|rd)/,
               relativeTime: {
                 future: 'in %s',
                 past: '%s ago',
                 s: 'a few seconds',
                 ss: '%d seconds',
                 m: 'a minute',
                 mm: '%d minutes',
                 h: 'an hour',
                 hh: '%d hours',
                 d: 'a day',
                 dd: '%d days',
                 w: 'a week',
                 ww: '%d weeks',
                 M: 'a month',
                 MM: '%d months',
                 y: 'a year',
                 yy: '%d years'
               },
               months: [
                 'January',
                 'February',
                 'March',
                 'April',
                 'May',
                 'June',
                 'July',
                 'August',
                 'September',
                 'October',
                 'November',
                 'December'
               ],
               monthsShort: [
                 'Jan',
                 'Feb',
                 'Mar',
                 'Apr',
                 'May',
                 'Jun',
                 'Jul',
                 'Aug',
                 'Sep',
                 'Oct',
                 'Nov',
                 'Dec'
               ],
               week: {
                 dow: 0,
                 doy: 6
               },
               weekdays: [
                 'Sunday',
                 'Monday',
                 'Tuesday',
                 'Wednesday',
                 'Thursday',
                 'Friday',
                 'Saturday'
               ],
               weekdaysMin: [
                 'Su',
                 'Mo',
                 'Tu',
                 'We',
                 'Th',
                 'Fr',
                 'Sa'
               ],
               weekdaysShort: [
                 'Sun',
                 'Mon',
                 'Tue',
                 'Wed',
                 'Thu',
                 'Fri',
                 'Sat'
               ],
               meridiemParse: /[ap]\.?m?\.?/i,
               eras: [
                 {
                   since: '0001-01-01',
                   until: Infinity,
                   offset: 1,
                   name: 'Anno Domini',
                   narrow: 'AD',
                   abbr: 'AD'
                 },
                 {
                   since: '0000-12-31',
                   until: -Infinity,
                   offset: 1,
                   name: 'Before Christ',
                   narrow: 'BC',
                   abbr: 'BC'
                 }
               ],
               abbr: 'en'
             },
             _dayOfMonthOrdinalParseLenient: /\d{1,2}(th|st|nd|rd)|\d{1,2}/
           },
           _d: new Date('2022-12-16T18:46:43.323Z'),
           ~~
           _isValid: true
           ~~~~~~~~
         }
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       }
     })

Unknown arg `scope` in data.scope for type ZohoTokenUpdateInput. Did you mean `select`? Available args:
type ZohoTokenUpdateInput {
  access_token?: String | StringFieldUpdateOperationsInput
  refresh_token?: String | StringFieldUpdateOperationsInput
  expires_in?: String | StringFieldUpdateOperationsInput
}
Unknown arg `api_domain` in data.api_domain for type ZohoTokenUpdateInput. Did you mean `expires_in`? Available args:
type ZohoTokenUpdateInput {
  access_token?: String | StringFieldUpdateOperationsInput
  refresh_token?: String | StringFieldUpdateOperationsInput
  expires_in?: String | StringFieldUpdateOperationsInput
}
Unknown arg `token_type` in data.token_type for type ZohoTokenUpdateInput. Did you mean `access_token`? Available args:
type ZohoTokenUpdateInput {
  access_token?: String | StringFieldUpdateOperationsInput
  refresh_token?: String | StringFieldUpdateOperationsInput
  expires_in?: String | StringFieldUpdateOperationsInput
}
Argument data.expires_in of type StringFieldUpdateOperationsInput needs exactly one argument, but you provided _isAMomentObject and _isUTC and _pf and _locale and _d and _isValid. Please choose one. Available args: 
type StringFieldUpdateOperationsInput {
  set?: String
}
Unknown arg `_isAMomentObject` in data.expires_in._isAMomentObject for type StringFieldUpdateOperationsInput. Available args:

type StringFieldUpdateOperationsInput {
  set?: String
}
Unknown arg `_isUTC` in data.expires_in._isUTC for type StringFieldUpdateOperationsInput. Did you mean `set`? Available args:
type StringFieldUpdateOperationsInput {
  set?: String
}
Unknown arg `_pf` in data.expires_in._pf for type StringFieldUpdateOperationsInput. Did you mean `set`? Available args:
type StringFieldUpdateOperationsInput {
  set?: String
}
Unknown arg `_locale` in data.expires_in._locale for type StringFieldUpdateOperationsInput. Did you mean `select`? Available args:
type StringFieldUpdateOperationsInput {
  set?: String
}
Unknown arg `_d` in data.expires_in._d for type StringFieldUpdateOperationsInput. Available args:

type StringFieldUpdateOperationsInput {
  set?: String
}
Unknown arg `_isValid` in data.expires_in._isValid for type StringFieldUpdateOperationsInput. Did you mean `set`? Available args:
type StringFieldUpdateOperationsInput {
  set?: String
}


AHUB API:ERROR [Dec-16-2022 19:07:37] Error Generating Zoho Code: Error: 
Invalid `prisma_1.Prisma.zohoToken.update()` invocation in
E:\Projects\servers\ahub-api\dist\Services\ZohoService.js:71:65

  68 Libs_1.Logger.info('Refreshing Token');
  69 const { data } = yield Axios.post(`https://accounts.zoho.com/oauth/v2/token?client_id=${config_1.zohoCrmConfig.clientID}&client_secret=${config_1.zohoCrmConfig.clientSecret}&grant_type=refresh_token&refresh_token=${refresh_token}&scope=${config_1.zohoCrmConfig.scope}`);
  70 data.expires_in = addMinutes();
â†’ 71 const updated = yield prisma_1.Prisma.zohoToken.update({
       where: {
         id: '639ca03111f43a1124787cb6'
       },
       data: {
         access_token: '1000.c60431c456f0741cbdd952c8a9125c16.ae2252a06419f76ab1febbae604ea319',
         refresh_token: undefined,
         expires_in: {
           _isAMomentObject: true,
           ~~~~~~~~~~~~~~~~
           _isUTC: false,
           ~~~~~~
           _pf: {
           ~~~
             empty: false,
             unusedTokens: [],
             unusedInput: [],
             overflow: -2,
             charsLeftOver: 0,
             nullInput: false,
             invalidEra: null,
             invalidMonth: null,
             invalidFormat: false,
             userInvalidated: false,
             iso: false,
             parsedDateParts: [],
             era: null,
             meridiem: null,
             rfc2822: false,
             weekdayMismatch: false
           },
           _locale: {
           ~~~~~~~
             _calendar: {
               sameDay: '[Today at] LT',
               nextDay: '[Tomorrow at] LT',
               nextWeek: 'dddd [at] LT',
               lastDay: '[Yesterday at] LT',
               lastWeek: '[Last] dddd [at] LT',
               sameElse: 'L'
             },
             _longDateFormat: {
               LTS: 'h:mm:ss A',
               LT: 'h:mm A',
               L: 'MM/DD/YYYY',
               LL: 'MMMM D, YYYY',
               LLL: 'MMMM D, YYYY h:mm A',
               LLLL: 'dddd, MMMM D, YYYY h:mm A'
             },
             _invalidDate: 'Invalid date',
             ordinal: function (number) {
                 var b = number % 10,
                     output =
                         toInt((number % 100) / 10) === 1
                             ? 'th'
                             : b === 1
                             ? 'st'
                             : b === 2
                             ? 'nd'
                             : b === 3
                             ? 'rd'
                             : 'th';
                 return number + output;
             },
             _dayOfMonthOrdinalParse: /\d{1,2}(th|st|nd|rd)/,
             _relativeTime: {
               future: 'in %s',
               past: '%s ago',
               s: 'a few seconds',
               ss: '%d seconds',
               m: 'a minute',
               mm: '%d minutes',
               h: 'an hour',
               hh: '%d hours',
               d: 'a day',
               dd: '%d days',
               w: 'a week',
               ww: '%d weeks',
               M: 'a month',
               MM: '%d months',
               y: 'a year',
               yy: '%d years'
             },
             _months: [
               'January',
               'February',
               'March',
               'April',
               'May',
               'June',
               'July',
               'August',
               'September',
               'October',
               'November',
               'December'
             ],
             _monthsShort: [
               'Jan',
               'Feb',
               'Mar',
               'Apr',
               'May',
               'Jun',
               'Jul',
               'Aug',
               'Sep',
               'Oct',
               'Nov',
               'Dec'
             ],
             _week: {
               dow: 0,
               doy: 6
             },
             _weekdays: [
               'Sunday',
               'Monday',
               'Tuesday',
               'Wednesday',
               'Thursday',
               'Friday',
               'Saturday'
             ],
             _weekdaysMin: [
               'Su',
               'Mo',
               'Tu',
               'We',
               'Th',
               'Fr',
               'Sa'
             ],
             _weekdaysShort: [
               'Sun',
               'Mon',
               'Tue',
               'Wed',
               'Thu',
               'Fri',
               'Sat'
             ],
             _meridiemParse: /[ap]\.?m?\.?/i,
             _eras: [
               {
                 since: '0001-01-01',
                 until: Infinity,
                 offset: 1,
                 name: 'Anno Domini',
                 narrow: 'AD',
                 abbr: 'AD'
               },
               {
                 since: '0000-12-31',
                 until: -Infinity,
                 offset: 1,
                 name: 'Before Christ',
                 narrow: 'BC',
                 abbr: 'BC'
               }
             ],
             _abbr: 'en',
             _config: {
               calendar: {
                 sameDay: '[Today at] LT',
                 nextDay: '[Tomorrow at] LT',
                 nextWeek: 'dddd [at] LT',
                 lastDay: '[Yesterday at] LT',
                 lastWeek: '[Last] dddd [at] LT',
                 sameElse: 'L'
               },
               longDateFormat: {
                 LTS: 'h:mm:ss A',
                 LT: 'h:mm A',
                 L: 'MM/DD/YYYY',
                 LL: 'MMMM D, YYYY',
                 LLL: 'MMMM D, YYYY h:mm A',
                 LLLL: 'dddd, MMMM D, YYYY h:mm A'
               },
               invalidDate: 'Invalid date',
               ordinal: function (number) {
                 var b = number % 10,
                     output =
                         toInt((number % 100) / 10) === 1
                             ? 'th'
                             : b === 1
                             ? 'st'
                             : b === 2
                             ? 'nd'
                             : b === 3
                             ? 'rd'
                             : 'th';
                 return number + output;
             },
               dayOfMonthOrdinalParse: /\d{1,2}(th|st|nd|rd)/,
               relativeTime: {
                 future: 'in %s',
                 past: '%s ago',
                 s: 'a few seconds',
                 ss: '%d seconds',
                 m: 'a minute',
                 mm: '%d minutes',
                 h: 'an hour',
                 hh: '%d hours',
                 d: 'a day',
                 dd: '%d days',
                 w: 'a week',
                 ww: '%d weeks',
                 M: 'a month',
                 MM: '%d months',
                 y: 'a year',
                 yy: '%d years'
               },
               months: [
                 'January',
                 'February',
                 'March',
                 'April',
                 'May',
                 'June',
                 'July',
                 'August',
                 'September',
                 'October',
                 'November',
                 'December'
               ],
               monthsShort: [
                 'Jan',
                 'Feb',
                 'Mar',
                 'Apr',
                 'May',
                 'Jun',
                 'Jul',
                 'Aug',
                 'Sep',
                 'Oct',
                 'Nov',
                 'Dec'
               ],
               week: {
                 dow: 0,
                 doy: 6
               },
               weekdays: [
                 'Sunday',
                 'Monday',
                 'Tuesday',
                 'Wednesday',
                 'Thursday',
                 'Friday',
                 'Saturday'
               ],
               weekdaysMin: [
                 'Su',
                 'Mo',
                 'Tu',
                 'We',
                 'Th',
                 'Fr',
                 'Sa'
               ],
               weekdaysShort: [
                 'Sun',
                 'Mon',
                 'Tue',
                 'Wed',
                 'Thu',
                 'Fri',
                 'Sat'
               ],
               meridiemParse: /[ap]\.?m?\.?/i,
               eras: [
                 {
                   since: '0001-01-01',
                   until: Infinity,
                   offset: 1,
                   name: 'Anno Domini',
                   narrow: 'AD',
                   abbr: 'AD'
                 },
                 {
                   since: '0000-12-31',
                   until: -Infinity,
                   offset: 1,
                   name: 'Before Christ',
                   narrow: 'BC',
                   abbr: 'BC'
                 }
               ],
               abbr: 'en'
             },
             _dayOfMonthOrdinalParseLenient: /\d{1,2}(th|st|nd|rd)|\d{1,2}/
           },
           _d: new Date('2022-12-16T19:02:37.890Z'),
           ~~
           _isValid: true
           ~~~~~~~~
         }
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       }
     })

Argument data.expires_in of type StringFieldUpdateOperationsInput needs exactly one argument, but you provided _isAMomentObject and _isUTC and _pf and _locale and _d and _isValid. Please choose one. Available args: 
type StringFieldUpdateOperationsInput {
  set?: String
}
Unknown arg `_isAMomentObject` in data.expires_in._isAMomentObject for type StringFieldUpdateOperationsInput. Available args:

type StringFieldUpdateOperationsInput {
  set?: String
}
Unknown arg `_isUTC` in data.expires_in._isUTC for type StringFieldUpdateOperationsInput. Did you mean `set`? Available args:
type StringFieldUpdateOperationsInput {
  set?: String
}
Unknown arg `_pf` in data.expires_in._pf for type StringFieldUpdateOperationsInput. Did you mean `set`? Available args:
type StringFieldUpdateOperationsInput {
  set?: String
}
Unknown arg `_locale` in data.expires_in._locale for type StringFieldUpdateOperationsInput. Did you mean `select`? Available args:
type StringFieldUpdateOperationsInput {
  set?: String
}
Unknown arg `_d` in data.expires_in._d for type StringFieldUpdateOperationsInput. Available args:

type StringFieldUpdateOperationsInput {
  set?: String
}
Unknown arg `_isValid` in data.expires_in._isValid for type StringFieldUpdateOperationsInput. Did you mean `set`? Available args:
type StringFieldUpdateOperationsInput {
  set?: String
}


AHUB API:ERROR [Dec-17-2022 03:02:56] Error Generating Zoho Code: Error: 
Invalid `prisma_1.Prisma.zohoToken.update()` invocation in
E:\Projects\servers\ahub-api\dist\Services\ZohoService.js:71:65

  68 Libs_1.Logger.info('Refreshing Token');
  69 const { data } = yield Axios.post(`https://accounts.zoho.com/oauth/v2/token?client_id=${config_1.zohoCrmConfig.clientID}&client_secret=${config_1.zohoCrmConfig.clientSecret}&grant_type=refresh_token&refresh_token=${refresh_token}&scope=${config_1.zohoCrmConfig.scope}`);
  70 data.expires_in = addMinutes();
â†’ 71 const updated = yield prisma_1.Prisma.zohoToken.update({
       where: {
         id: '639ca03111f43a1124787cb6'
       },
       data: {
         access_token: '1000.25f59d7c4a488ff6e5c684dc3678bca8.500a52ccdad02e45db2ce3054783387b',
         refresh_token: undefined,
         expires_in: {
           _isAMomentObject: true,
           ~~~~~~~~~~~~~~~~
           _isUTC: false,
           ~~~~~~
           _pf: {
           ~~~
             empty: false,
             unusedTokens: [],
             unusedInput: [],
             overflow: -2,
             charsLeftOver: 0,
             nullInput: false,
             invalidEra: null,
             invalidMonth: null,
             invalidFormat: false,
             userInvalidated: false,
             iso: false,
             parsedDateParts: [],
             era: null,
             meridiem: null,
             rfc2822: false,
             weekdayMismatch: false
           },
           _locale: {
           ~~~~~~~
             _calendar: {
               sameDay: '[Today at] LT',
               nextDay: '[Tomorrow at] LT',
               nextWeek: 'dddd [at] LT',
               lastDay: '[Yesterday at] LT',
               lastWeek: '[Last] dddd [at] LT',
               sameElse: 'L'
             },
             _longDateFormat: {
               LTS: 'h:mm:ss A',
               LT: 'h:mm A',
               L: 'MM/DD/YYYY',
               LL: 'MMMM D, YYYY',
               LLL: 'MMMM D, YYYY h:mm A',
               LLLL: 'dddd, MMMM D, YYYY h:mm A'
             },
             _invalidDate: 'Invalid date',
             ordinal: function (number) {
                 var b = number % 10,
                     output =
                         toInt((number % 100) / 10) === 1
                             ? 'th'
                             : b === 1
                             ? 'st'
                             : b === 2
                             ? 'nd'
                             : b === 3
                             ? 'rd'
                             : 'th';
                 return number + output;
             },
             _dayOfMonthOrdinalParse: /\d{1,2}(th|st|nd|rd)/,
             _relativeTime: {
               future: 'in %s',
               past: '%s ago',
               s: 'a few seconds',
               ss: '%d seconds',
               m: 'a minute',
               mm: '%d minutes',
               h: 'an hour',
               hh: '%d hours',
               d: 'a day',
               dd: '%d days',
               w: 'a week',
               ww: '%d weeks',
               M: 'a month',
               MM: '%d months',
               y: 'a year',
               yy: '%d years'
             },
             _months: [
               'January',
               'February',
               'March',
               'April',
               'May',
               'June',
               'July',
               'August',
               'September',
               'October',
               'November',
               'December'
             ],
             _monthsShort: [
               'Jan',
               'Feb',
               'Mar',
               'Apr',
               'May',
               'Jun',
               'Jul',
               'Aug',
               'Sep',
               'Oct',
               'Nov',
               'Dec'
             ],
             _week: {
               dow: 0,
               doy: 6
             },
             _weekdays: [
               'Sunday',
               'Monday',
               'Tuesday',
               'Wednesday',
               'Thursday',
               'Friday',
               'Saturday'
             ],
             _weekdaysMin: [
               'Su',
               'Mo',
               'Tu',
               'We',
               'Th',
               'Fr',
               'Sa'
             ],
             _weekdaysShort: [
               'Sun',
               'Mon',
               'Tue',
               'Wed',
               'Thu',
               'Fri',
               'Sat'
             ],
             _meridiemParse: /[ap]\.?m?\.?/i,
             _eras: [
               {
                 since: '0001-01-01',
                 until: Infinity,
                 offset: 1,
                 name: 'Anno Domini',
                 narrow: 'AD',
                 abbr: 'AD'
               },
               {
                 since: '0000-12-31',
                 until: -Infinity,
                 offset: 1,
                 name: 'Before Christ',
                 narrow: 'BC',
                 abbr: 'BC'
               }
             ],
             _abbr: 'en',
             _config: {
               calendar: {
                 sameDay: '[Today at] LT',
                 nextDay: '[Tomorrow at] LT',
                 nextWeek: 'dddd [at] LT',
                 lastDay: '[Yesterday at] LT',
                 lastWeek: '[Last] dddd [at] LT',
                 sameElse: 'L'
               },
               longDateFormat: {
                 LTS: 'h:mm:ss A',
                 LT: 'h:mm A',
                 L: 'MM/DD/YYYY',
                 LL: 'MMMM D, YYYY',
                 LLL: 'MMMM D, YYYY h:mm A',
                 LLLL: 'dddd, MMMM D, YYYY h:mm A'
               },
               invalidDate: 'Invalid date',
               ordinal: function (number) {
                 var b = number % 10,
                     output =
                         toInt((number % 100) / 10) === 1
                             ? 'th'
                             : b === 1
                             ? 'st'
                             : b === 2
                             ? 'nd'
                             : b === 3
                             ? 'rd'
                             : 'th';
                 return number + output;
             },
               dayOfMonthOrdinalParse: /\d{1,2}(th|st|nd|rd)/,
               relativeTime: {
                 future: 'in %s',
                 past: '%s ago',
                 s: 'a few seconds',
                 ss: '%d seconds',
                 m: 'a minute',
                 mm: '%d minutes',
                 h: 'an hour',
                 hh: '%d hours',
                 d: 'a day',
                 dd: '%d days',
                 w: 'a week',
                 ww: '%d weeks',
                 M: 'a month',
                 MM: '%d months',
                 y: 'a year',
                 yy: '%d years'
               },
               months: [
                 'January',
                 'February',
                 'March',
                 'April',
                 'May',
                 'June',
                 'July',
                 'August',
                 'September',
                 'October',
                 'November',
                 'December'
               ],
               monthsShort: [
                 'Jan',
                 'Feb',
                 'Mar',
                 'Apr',
                 'May',
                 'Jun',
                 'Jul',
                 'Aug',
                 'Sep',
                 'Oct',
                 'Nov',
                 'Dec'
               ],
               week: {
                 dow: 0,
                 doy: 6
               },
               weekdays: [
                 'Sunday',
                 'Monday',
                 'Tuesday',
                 'Wednesday',
                 'Thursday',
                 'Friday',
                 'Saturday'
               ],
               weekdaysMin: [
                 'Su',
                 'Mo',
                 'Tu',
                 'We',
                 'Th',
                 'Fr',
                 'Sa'
               ],
               weekdaysShort: [
                 'Sun',
                 'Mon',
                 'Tue',
                 'Wed',
                 'Thu',
                 'Fri',
                 'Sat'
               ],
               meridiemParse: /[ap]\.?m?\.?/i,
               eras: [
                 {
                   since: '0001-01-01',
                   until: Infinity,
                   offset: 1,
                   name: 'Anno Domini',
                   narrow: 'AD',
                   abbr: 'AD'
                 },
                 {
                   since: '0000-12-31',
                   until: -Infinity,
                   offset: 1,
                   name: 'Before Christ',
                   narrow: 'BC',
                   abbr: 'BC'
                 }
               ],
               abbr: 'en'
             },
             _dayOfMonthOrdinalParseLenient: /\d{1,2}(th|st|nd|rd)|\d{1,2}/
           },
           _d: new Date('2022-12-17T02:57:56.729Z'),
           ~~
           _isValid: true
           ~~~~~~~~
         }
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       }
     })

Argument data.expires_in of type StringFieldUpdateOperationsInput needs exactly one argument, but you provided _isAMomentObject and _isUTC and _pf and _locale and _d and _isValid. Please choose one. Available args: 
type StringFieldUpdateOperationsInput {
  set?: String
}
Unknown arg `_isAMomentObject` in data.expires_in._isAMomentObject for type StringFieldUpdateOperationsInput. Available args:

type StringFieldUpdateOperationsInput {
  set?: String
}
Unknown arg `_isUTC` in data.expires_in._isUTC for type StringFieldUpdateOperationsInput. Did you mean `set`? Available args:
type StringFieldUpdateOperationsInput {
  set?: String
}
Unknown arg `_pf` in data.expires_in._pf for type StringFieldUpdateOperationsInput. Did you mean `set`? Available args:
type StringFieldUpdateOperationsInput {
  set?: String
}
Unknown arg `_locale` in data.expires_in._locale for type StringFieldUpdateOperationsInput. Did you mean `select`? Available args:
type StringFieldUpdateOperationsInput {
  set?: String
}
Unknown arg `_d` in data.expires_in._d for type StringFieldUpdateOperationsInput. Available args:

type StringFieldUpdateOperationsInput {
  set?: String
}
Unknown arg `_isValid` in data.expires_in._isValid for type StringFieldUpdateOperationsInput. Did you mean `set`? Available args:
type StringFieldUpdateOperationsInput {
  set?: String
}


AHUB API:ERROR [Dec-17-2022 03:04:18] Error Creating Zoho Ticket: {"errorCode":"INVALID_OAUTH","message":"The OAuth Token you provided is invalid."}
AHUB API:ERROR [Dec-17-2022 03:06:31] Error Creating Zoho Ticket: {"errorCode":"INVALID_OAUTH","message":"The OAuth Token you provided is invalid."}
